SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE view [dbo].[vw_ExistenciasBase]

as
	SELECT 
			INVE_CLIB01.CAMPLIB4 AS CAMPOINTU,
			substring(INVE01.CVE_ART,1,8) as ART_DESC,
			right(INVE01.CVE_ART,4) as ART_TALLA,
			MULT01.CVE_ALM AS ALMACEN,
			MULT01.CVE_ART AS CLV_ART,
			INVE01.DESCR,
			MULT01.EXIST,
			MULT01.COMP_X_REC,
			MULT01.STOCK_MIN,
			MULT01.STOCK_MAX,
			PEND_SURT,
			LTRIM(RTRIM(INVE_CLIB01.CAMPLIB1)) AS CAMPOSTRU1,
			INVE01.CVE_ART AS INVE01_CVE_ART
	FROM 
			aspel_sae50.dbo.INVE01
		JOIN
			aspel_sae50.dbo.INVE_CLIB01
			ON
			INVE01.CVE_ART = INVE_CLIB01.CVE_PROD
		JOIN
			aspel_sae50.dbo.MULT01
			ON
			INVE01.CVE_ART = MULT01.CVE_ART
	WHERE
			LTRIM(RTRIM(INVE_CLIB01.CAMPLIB1)) <> ''
		AND
			TIPO_ELE = 'P'
		AND
			INVE01.STATUS = 'A'
		
GO
