SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date,,>
-- Description:	<Description,,>
-- =============================================
CREATE PROCEDURE [dbo].[usp_RepPromCobra]
	@Agente varchar(10)
AS
BEGIN

-- guarda en temporales datos

	SELECT CLIE01.CLAVE AS CCLIE,NOMBRE,SALDO,CVE_VEND AS VEND INTO #CLIENTES From aspel_sae50.dbo.CLIE01 WHERE SALDO <> 0 ORDER BY CCLIE

	SELECT CVE_CLIE AS CCLIE,REFER,SIGNO AS TIPO,SUM(IMPORTE) AS CARGOS INTO #CARGOS FROM aspel_sae50.dbo.CUEN_M01 WHERE CVE_CLIE IN(SELECT CCLIE FROM #CLIENTES) AND SIGNO = 1 GROUP BY CVE_CLIE,REFER,SIGNO

	SELECT CVE_CLIE AS CCLIE,REFER,SIGNO AS TIPO,SUM(IMPORTE) AS ABONOS INTO #ABONOS FROM aspel_sae50.dbo.CUEN_DET01 WHERE CVE_CLIE IN(SELECT CCLIE FROM #CLIENTES) AND SIGNO = -1 GROUP BY CVE_CLIE,REFER,SIGNO


-- aqui inicia la consulta final desde las tablas temporales anteriores

select CLIENTES.CCLIE, CLIENTES.NOMBRE, CLIENTES.SALDO SALDO, Con1.REFER FACTURA, CUEN_M01.FECHA_APLI F_ELAB, CUEN_M01.FECHA_VENC F_VENC, (Sum(CARGOS)-Sum(ABONOS)) CARGO, DATEDIFF(DAY,CUEN_M01.FECHA_VENC, GETDATE()) DIAS_VENC  from (

select CCLIE CCLIE, REFER REFER, CARGOS AS CARGOS, 0 as ABONOS from #CARGOS 
union
select CCLIE CCLIE, REFER REFER, 0 as CARGOS, ABONOS as ABONOS from #ABONOS) as Con1

INNER JOIN #CLIENTES CLIENTES on Con1.CCLIE = CLIENTES.CCLIE

INNER JOIN aspel_sae50.dbo.CUEN_M01 on Con1.CCLIE = CUEN_M01.CVE_CLIE and CUEN_M01.REFER = Con1.REFER

where CLIENTES.VEND = @Agente

group by CLIENTES.CCLIE, CLIENTES.NOMBRE, CLIENTES.SALDO, Con1.REFER, CUEN_M01.FECHA_APLI, CUEN_M01.FECHA_VENC

having ((Sum(convert(decimal(12,2),CARGOS))-Sum(convert(decimal(12,2),ABONOS))))<>0

order by CLIENTES.CCLIE

drop table #CLIENTES
drop table #CARGOS
drop table #ABONOS

END
GO
