
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date,,>
-- Description:	<Description,,>
--27-Abr-2015 : Se cambia F_ENTREGADO por F_EMBARQUE en Fch Real y pedidos tipo OV
-- =============================================
CREATE PROCEDURE [dbo].[usp_RepFechasYDesempeñoPorArea]
	(
		@fecha_inicial		as	datetime,
		@fecha_final		as	datetime
	)
AS
BEGIN	
	SET NOCOUNT ON

		SELECT 
			U.F_GESTION AS 'Fch Ing',
			U.PEDIDO AS Pedido,
			P.AGENTE AS Agte,
			CL.NOMBRE AS 'Razón Social',
			ISNULL(P.PRENDAS,0) AS 'Pren',
			ISNULL(U.PROCESOS,'') AS 'Proc',
			ISNULL(CONVERT(VARCHAR,ESTDPEDI.ADVO),'--') AS ADVO,
			ISNULL(CONVERT(VARCHAR,ESTDPEDI.LIB,0),'--') AS LIB,
			ISNULL(CONVERT(VARCHAR,ESTDPEDI.SUR,0),'--') AS SUR,
			ISNULL(CONVERT(VARCHAR,ESTDPEDI.COR * (SELECT COUNT(DISTINCT(CMT_PROCESO)) FROM aspel_sae50.dbo.CMT_DET WHERE CMT_PEDIDO = U.PEDIDO AND CMT_PROCESO = 'R'),0),'--') AS COR,
			ISNULL(CONVERT(VARCHAR,ESTDPEDI.EST * (SELECT COUNT(DISTINCT(CMT_PROCESO)) FROM aspel_sae50.dbo.CMT_DET WHERE CMT_PEDIDO = U.PEDIDO AND CMT_PROCESO = 'E'),0),'--') AS EST,
			ISNULL(CONVERT(VARCHAR,ESTDPEDI.BOR * (SELECT COUNT(DISTINCT(CMT_PROCESO)) FROM aspel_sae50.dbo.CMT_DET WHERE CMT_PEDIDO = U.PEDIDO AND CMT_PROCESO = 'B'),0),'--') AS BOR,
			ISNULL(CONVERT(VARCHAR,ESTDPEDI.INI * (SELECT COUNT(DISTINCT(CMT_PROCESO)) FROM aspel_sae50.dbo.CMT_DET WHERE CMT_PEDIDO = U.PEDIDO AND CMT_PROCESO = 'I'),0),'--') AS INI,
			ISNULL(CONVERT(VARCHAR,ESTDPEDI.COS * (SELECT COUNT(DISTINCT(CMT_PROCESO)) FROM aspel_sae50.dbo.CMT_DET WHERE CMT_PEDIDO = U.PEDIDO AND CMT_PROCESO = 'C'),0),'--') AS COS,
			ISNULL(CONVERT(VARCHAR,ESTDPEDI.EMP,0),'--') AS EMP,
			ISNULL(CONVERT(VARCHAR,ESTDPEDI.EMB,0),'--') AS EMB,
			ISNULL(CONVERT(VARCHAR,ESTDPEDI.ESP,0),'--') AS ESP,
			U.F_VENCIMIENTO AS 'Fch Prog.',
			U.F_ENTREGADO AS 'Fch Real',
			U.F_ASIG_RUTA AS 'Fch Ruta',
			U.F_LIBERADO AS 'Fch Lib.',
			U.F_SURTIDO AS 'Fch Surt.',
			ISNULL(REPLACE(REPLACE(U.OBSERVACIONES,CHAR(10),' '),CHAR(13),' '),'')+ISNULL(REPLACE(REPLACE(COM_ENTREGA,CHAR(10),' '),CHAR(13),' '),'') AS Observaciones,
			ISNULL(COMENTARIOS,'') COMENTARIOS,			
			ISNULL((SELECT OBSERVACIONES FROM aspel_sae50.dbo.DESEMBYAREA DE WHERE DE.PEDIDO=U.PEDIDO AND DEPTO='Ventas'), '') AS 'Obser. Ventas',
			ISNULL((SELECT OBSERVACIONES FROM aspel_sae50.dbo.DESEMBYAREA DE WHERE DE.PEDIDO=U.PEDIDO AND DEPTO='Almacen'), '') AS 'Obser. Almacén',
			ISNULL((SELECT OBSERVACIONES FROM aspel_sae50.dbo.DESEMBYAREA DE WHERE DE.PEDIDO=U.PEDIDO AND DEPTO='Compras'), '') AS 'Obser. Compras',
			ISNULL((SELECT OBSERVACIONES FROM aspel_sae50.dbo.DESEMBYAREA DE WHERE DE.PEDIDO=U.PEDIDO AND DEPTO='Sistemas'), '') AS 'Obser. Sistemas',
			ISNULL((SELECT OBSERVACIONES FROM aspel_sae50.dbo.DESEMBYAREA DE WHERE DE.PEDIDO=U.PEDIDO AND DEPTO='Operaciones'), '') AS 'Obser. Operaciones',
			ISNULL((SELECT OBSERVACIONES FROM aspel_sae50.dbo.DESEMBYAREA DE WHERE DE.PEDIDO=U.PEDIDO AND DEPTO='Credito'), '') AS 'Obser. Crédito',
			ISNULL((SELECT OBSERVACIONES FROM aspel_sae50.dbo.DESEMBYAREA DE WHERE DE.PEDIDO=U.PEDIDO AND DEPTO='Cliente'), '') AS 'Obser. Cliente'
		FROM 
				aspel_sae50.dbo.UPPEDIDOS as U
			INNER JOIN
				aspel_sae50.dbo.PED_MSTR P ON U.PEDIDO = P.PEDIDO AND P.TIPO = 'OV'
			INNER JOIN
				aspel_sae50.dbo.CLIE01 CL ON LTRIM(RTRIM(P.CLIENTE)) =LTRIM(RTRIM(CL.CLAVE))
			LEFT JOIN
				aspel_sae50.dbo.ESTDPEDI ON P.PEDIDO = ESTDPEDI.PEDIDO
		WHERE 
			convert(datetime2,convert(varchar(255),F_VENCIMIENTO,103),103)  BETWEEN @fecha_inicial AND @fecha_final
		ORDER BY 
			U.PEDIDO
	
END
GO
