CREATE TABLE [dbo].[LogUPPedidos](
	[UID] [int] IDENTITY(1,1) NOT NULL,
	[TRAN_ID] [int] default(0) not null,
	[WIN_USER] [varchar](50) not null,
	[SIP80_USER] [varchar](50) not null,
	[PC] [varchar](50) not null,
	[DATE] [datetime] not null,	
	[ACCION] [varchar](20) not null,
	[PANTALLA] [varchar](100) not null,
	[ID] [int] NULL,
	[PEDIDO] [float] NULL,
	[COD_CLIENTE] [varchar](50) NULL,
	[F_VENCIMIENTO] [smalldatetime] NULL,
	[F_VENCIMIENTO2] [smalldatetime] NULL,
	[F_ESTANDAR] [smalldatetime] NULL,
	[PROCESOS] [varchar](50) NULL,
	[COMENTARIOS] [varchar](255) NULL,
	[F_CAPT] [smalldatetime] NULL,
	[F_IMPRESION] [smalldatetime] NULL,
	[F_GESTION] [smalldatetime] NULL,
	[F_CAPT_ASPEL] [smalldatetime] NULL,
	[F_CREDITO] [smalldatetime] NULL,
	[F_ASIG_RUTA] [smalldatetime] NULL,
	[F_LIBERADO] [smalldatetime] NULL,
	[F_SURTIDO] [smalldatetime] NULL,
	[F_BORDADO] [smalldatetime] NULL,
	[F_COSTURA] [smalldatetime] NULL,
	[F_CORTE] [smalldatetime] NULL,
	[F_ESTAMPADO] [smalldatetime] NULL,
	[F_INICIALES] [smalldatetime] NULL,
	[F_EMPAQUE] [smalldatetime] NULL,
	[F_EMBARQUE] [smalldatetime] NULL,
	[FECHAPEDIDO] [smalldatetime] NULL,
	[FECHARUTA] [smalldatetime] NULL,
	[GUIA] [varchar](50) NULL,
	[CAJAS] [int] NULL,
	[CHOFER] [varchar](20) NULL,
	[DEPARTAMENTO] [varchar](50) NULL,
	[DESTINO] [varchar](30) NULL,
	[OBSERVACIONES] [varchar](max) NULL,
	[ESTATUS] [varchar](10) NULL,
	[TRANSPORTE] [varchar](20) NULL,
	[COM_SURTIDO] [varchar](255) NULL,
	[COM_BORDADO] [varchar](255) NULL,
	[COM_COSTURA] [varchar](255) NULL,
	[COM_CORTE] [varchar](255) NULL,
	[COM_ESTAMPADO] [varchar](255) NULL,
	[COM_INICIALES] [varchar](255) NULL,
	[COM_EMPAQUE] [varchar](255) NULL,
	[COM_CREDITO] [varchar](255) NULL,
	[ESTATUS_UPPEDIDOS] [varchar](1) NULL,
	[F_ENTREGADO] [smalldatetime] NULL,
	[COM_ENTREGA] [varchar](255) NULL,
 CONSTRAINT [PK_UPPEDIDOS] PRIMARY KEY CLUSTERED 
(
	[UID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) 