CREATE TABLE COST_MSTR (
	[NUM_REG] [int] IDENTITY(1,1) NOT NULL,
	[CVE_CLPV] [varchar](10) NOT NULL,
	[CVE_DOC] [varchar](20) NOT NULL,
	[CAN_TOT] [float] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[CVE_CLPV] ASC,
	[CVE_DOC] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]