SELECT 
	CMT.CMT_AGRUPADOR,
	CMT_PEDIDO
into
	#CMT_REPAIR
FROM
	aspel_sae50..PED_MSTR P
INNER JOIN
	aspel_sae50..CMT_DET CMT ON P.PEDIDO = CMT.CMT_PEDIDO  WHERE CMT.CMT_CLIENTE IS NULL AND YEAR(P.FECHA) = 2015 AND CMT_CMMT = 'FLETE' AND P.TIPO = 'OV'


SELECT 
	PED_DET.PEDIDO,
	substring(CODIGO,1,8) as MODELO,
	AGRUPADOR,
	PED_DET.PROCESOS AS RUTA,
	PED_MSTR.CLIENTE,
	PED_MSTR.ESTATUS,
	SUM(PED_DET.CANTIDAD) AS CANTIDAD	
into
	#M_DATA
FROM
	aspel_sae50..PED_DET
INNER JOIN
	aspel_sae50..PED_MSTR
	ON
	PED_DET.PEDIDO = PED_MSTR.PEDIDO
INNER JOIN 
	#CMT_REPAIR
	ON
	#CMT_REPAIR.CMT_PEDIDO = PED_DET.PEDIDO AND #CMT_REPAIR.CMT_AGRUPADOR = PED_DET.AGRUPADOR
group by substring(CODIGO,1,8),AGRUPADOR,PED_DET.PROCESOS,PED_MSTR.CLIENTE,PED_MSTR.ESTATUS,PED_DET.PEDIDO,PED_DET.AGRUPADOR, PED_MSTR.TIPO

--SELECT * FROM #M_DATA

UPDATE aspel_sae50..CMT_DET set
	CMT_MAQUILERO = 1,
	CMT_MODELO = #M_DATA.MODELO,	
	CMT_CLIENTE = #M_DATA.CLIENTE,
	CMT_RUTA = #M_DATA.RUTA,
	CMT_ESTATUS = #M_DATA.ESTATUS,
	CMT_CANTIDAD = #M_DATA.CANTIDAD,
	CMT_PRE_PROCESO = 0,
	CMT_COS_PROCESO = 0	
FROM
	#M_DATA
INNER JOIN	
	aspel_sae50..CMT_DET
	ON
	CMT_DET.CMT_PEDIDO = #M_DATA.PEDIDO
	AND
	CMT_DET.CMT_AGRUPADOR = #M_DATA.AGRUPADOR


--SELECT * FROM #CMT_REPAIR

DROP TABLE #CMT_REPAIR
DROP TABLE #M_DATA