//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ulp_dl.SIPPermisos
{
    using System;
    using System.Collections.Generic;
    
    public partial class PermisosModuloAtributos
    {
        public PermisosModuloAtributos()
        {
            this.PermisosUsuarioEspeciales = new HashSet<PermisosUsuarioEspeciales>();
        }
    
        public int Id { get; set; }
        public string AtributoNombre { get; set; }
        public string AtributoAccion { get; set; }
        public int ModuloId { get; set; }
    
        public virtual PermisosModulos PermisosModulos { get; set; }
        public virtual ICollection<PermisosUsuarioEspeciales> PermisosUsuarioEspeciales { get; set; }
    }
}
