//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ulp_dl.SIPPermisos
{
    using System;
    using System.Collections.Generic;
    
    public partial class PermisosUsuarios
    {
        public PermisosUsuarios()
        {
            this.PermisosGrupos = new HashSet<PermisosGrupos>();
            this.PermisosUsuarioEspeciales = new HashSet<PermisosUsuarioEspeciales>();
        }
    
        public int Id { get; set; }
        public string UsuarioUsuario { get; set; }
        public string UsuarioNombre { get; set; }
        public string UsuarioContraseña { get; set; }
        public string UsuarioCorreo { get; set; }
        public bool UsuarioStatus { get; set; }
        public System.DateTime UsuarioFechaIngreso { get; set; }
        public string UsuarioArea { get; set; }
    
        public virtual ICollection<PermisosGrupos> PermisosGrupos { get; set; }
        public virtual ICollection<PermisosUsuarioEspeciales> PermisosUsuarioEspeciales { get; set; }
    }
}
