//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ulp_dl.SIPPermisos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SIPPermisosContext : DbContext
    {
        public SIPPermisosContext()
            : base("name=SIPPermisosContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<PermisosGrupos> PermisosGrupos { get; set; }
        public DbSet<PermisosModuloAtributos> PermisosModuloAtributos { get; set; }
        public DbSet<PermisosModulos> PermisosModulos { get; set; }
        public DbSet<PermisosPerfiles> PermisosPerfiles { get; set; }
        public DbSet<PermisosPerfilModulos> PermisosPerfilModulos { get; set; }
        public DbSet<PermisosUsuarioEspeciales> PermisosUsuarioEspeciales { get; set; }
        public DbSet<PermisosUsuarioPerfiles> PermisosUsuarioPerfiles { get; set; }
        public DbSet<PermisosUsuarios> PermisosUsuarios { get; set; }
        public DbSet<vw_PermisosPorAtributo> vw_PermisosPorAtributo { get; set; }
    }
}
