//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ulp_dl.SIPPermisos
{
    using System;
    using System.Collections.Generic;
    
    public partial class PermisosGrupos
    {
        public PermisosGrupos()
        {
            this.PermisosModulos = new HashSet<PermisosModulos>();
        }
    
        public int Id { get; set; }
        public string GrupoNombre { get; set; }
        public int UsuarioId { get; set; }
    
        public virtual ICollection<PermisosModulos> PermisosModulos { get; set; }
        public virtual PermisosUsuarios PermisosUsuarios { get; set; }
    }
}
