//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ulp_dl.SIPReportes
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SIPReportesContext : DbContext
    {
        public SIPReportesContext()
            : base("name=SIPReportesContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<vw_FactFFoliosAntPrendas> vw_FactFFoliosAntPrendas { get; set; }
        public DbSet<vw_FactDFoliosAntPrendas> vw_FactDFoliosAntPrendas { get; set; }
        public DbSet<vw_UpPedidos> vw_UpPedidos { get; set; }
        public DbSet<vw_ExistenciasBase> vw_ExistenciasBase { get; set; }
        public DbSet<vw_Pedido> vw_Pedido { get; set; }
        public DbSet<vw_FactNVFoliosAntPrendas> vw_FactNVFoliosAntPrendas { get; set; }
    }
}
