//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ulp_dl.SIPReportes
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_ExistenciasBase
    {
        public int CAMPOINTU { get; set; }
        public string ART_DESC { get; set; }
        public string ART_TALLA { get; set; }
        public int ALMACEN { get; set; }
        public string CLV_ART { get; set; }
        public string DESCR { get; set; }
        public Nullable<double> EXIST { get; set; }
        public Nullable<double> COMP_X_REC { get; set; }
        public Nullable<double> STOCK_MIN { get; set; }
        public Nullable<double> STOCK_MAX { get; set; }
        public Nullable<double> PEND_SURT { get; set; }
        public string CAMPOSTRU1 { get; set; }
        public string INVE01_CVE_ART { get; set; }
    }
}
