//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ulp_dl.SIPReportes
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_FactFFoliosAntPrendas
    {
        public string CCLIE { get; set; }
        public string STATUS { get; set; }
        public Nullable<System.DateTime> FECHA_DOC { get; set; }
        public string CVE_DOC { get; set; }
        public string CVE_CLPV { get; set; }
        public string NOMBRE { get; set; }
        public string CVE_VEND { get; set; }
        public Nullable<double> SUBTOTAL { get; set; }
        public Nullable<double> IVA { get; set; }
        public Nullable<double> TOTAL { get; set; }
        public double PRENDAS { get; set; }
        public Nullable<int> FOLIO { get; set; }
    }
}
