//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ulp_dl.SIPReportes
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Pedido
    {
        public string CCLIE { get; set; }
        public string NOMBRE { get; set; }
        public string DIRECCION { get; set; }
        public string RFC { get; set; }
        public string ATENCION { get; set; }
        public int PEDIDO { get; set; }
        public string CLIENTE { get; set; }
        public System.DateTime FECHA { get; set; }
        public Nullable<double> DESCUENTO { get; set; }
        public string TERMINOS { get; set; }
        public Nullable<double> COMISION { get; set; }
        public string AGENTE { get; set; }
        public string ESTATUS { get; set; }
        public string REMITIDO { get; set; }
        public string CONSIGNADO { get; set; }
        public string OBSERVACIONES { get; set; }
        public Nullable<decimal> IMPORTE { get; set; }
        public Nullable<int> PRENDAS { get; set; }
        public Nullable<double> DESC_DADO { get; set; }
        public string OC { get; set; }
        public string MODELO { get; set; }
        public string DESCRIPCION { get; set; }
        public string TALLAS { get; set; }
        public Nullable<decimal> PRECIO { get; set; }
        public string AGRUPADOR { get; set; }
        public Nullable<decimal> PRE_PROCESOS { get; set; }
        public Nullable<int> CMT_PEDIDO { get; set; }
        public string CMT_CMMT { get; set; }
        public string CMT_PROCESO { get; set; }
        public Nullable<decimal> CMT_PRE_PROCESO { get; set; }
        public string CMT_AGRUPADOR { get; set; }
        public Nullable<int> t_PRENDAS { get; set; }
        public Nullable<int> t_PEDIDO { get; set; }
        public Nullable<decimal> t_IMPORTE { get; set; }
    }
}
