CREATE TABLE [dbo].[COST_ENLA]
(
[NUM_REG] [int] NOT NULL IDENTITY(1, 1),
[CVE_CLPV] [varchar] (10) COLLATE Modern_Spanish_CI_AS NOT NULL,
[CVE_DOC] [varchar] (20) COLLATE Modern_Spanish_CI_AS NOT NULL,
[PEDIDO] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[COST_ENLA] ADD CONSTRAINT [PK__COST_ENL__F1D431CC38EE7070] PRIMARY KEY CLUSTERED  ([CVE_CLPV], [CVE_DOC], [PEDIDO]) ON [PRIMARY]
GO
