CREATE TABLE [dbo].[tmp]
(
[ID] [int] NOT NULL,
[PEDIDO] [float] NOT NULL,
[COD_CLIENTE] [char] (10) COLLATE Latin1_General_BIN NULL,
[F_VENCIMIENTO] [smalldatetime] NULL,
[F_VENCIMIENTO2] [smalldatetime] NULL,
[F_ESTANDAR] [smalldatetime] NULL,
[PROCESOS] [varchar] (50) COLLATE Latin1_General_BIN NULL,
[COMENTARIOS] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[F_CAPT] [smalldatetime] NULL,
[F_IMPRESION] [smalldatetime] NULL,
[F_GESTION] [smalldatetime] NULL,
[F_CAPT_ASPEL] [smalldatetime] NULL,
[F_CREDITO] [smalldatetime] NULL,
[F_ASIG_RUTA] [smalldatetime] NULL,
[F_LIBERADO] [smalldatetime] NULL,
[F_SURTIDO] [smalldatetime] NULL,
[F_BORDADO] [smalldatetime] NULL,
[F_COSTURA] [smalldatetime] NULL,
[F_CORTE] [smalldatetime] NULL,
[F_ESTAMPADO] [smalldatetime] NULL,
[F_INICIALES] [smalldatetime] NULL,
[F_EMPAQUE] [smalldatetime] NULL,
[F_EMBARQUE] [smalldatetime] NULL,
[FECHAPEDIDO] [smalldatetime] NULL,
[FECHARUTA] [smalldatetime] NULL,
[GUIA] [char] (15) COLLATE Latin1_General_BIN NULL,
[CAJAS] [int] NULL,
[CHOFER] [varchar] (20) COLLATE Latin1_General_BIN NULL,
[DEPARTAMENTO] [varchar] (50) COLLATE Latin1_General_BIN NULL,
[DESTINO] [varchar] (30) COLLATE Latin1_General_BIN NULL,
[OBSERVACIONES] [text] COLLATE Latin1_General_BIN NULL,
[ESTATUS] [varchar] (10) COLLATE Latin1_General_BIN NULL,
[TRANSPORTE] [varchar] (20) COLLATE Latin1_General_BIN NULL,
[COM_SURTIDO] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[COM_BORDADO] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[COM_COSTURA] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[COM_CORTE] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[COM_ESTAMPADO] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[COM_INICIALES] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[COM_EMPAQUE] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[COM_CREDITO] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[ESTATUS_UPPEDIDOS] [varchar] (1) COLLATE Latin1_General_BIN NULL,
[F_ENTREGADO] [smalldatetime] NULL,
[COM_ENTREGA] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[NOMBRE] [varchar] (120) COLLATE Latin1_General_BIN NULL,
[TOT_PEDIDOS] [int] NULL,
[VEND] [varchar] (5) COLLATE Latin1_General_BIN NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
