CREATE TABLE [dbo].[LogUPPedidos]
(
[UID] [int] NOT NULL IDENTITY(1, 1),
[TRAN_ID] [int] NOT NULL CONSTRAINT [DF__LogUPPedi__TRAN___2B947552] DEFAULT ((0)),
[WIN_USER] [varchar] (50) COLLATE Modern_Spanish_CI_AS NOT NULL,
[SIP80_USER] [varchar] (50) COLLATE Modern_Spanish_CI_AS NOT NULL,
[PC] [varchar] (50) COLLATE Modern_Spanish_CI_AS NOT NULL,
[DATE] [datetime] NOT NULL,
[ACCION] [varchar] (20) COLLATE Modern_Spanish_CI_AS NOT NULL,
[PANTALLA] [varchar] (100) COLLATE Modern_Spanish_CI_AS NOT NULL,
[ID] [int] NULL,
[PEDIDO] [float] NULL,
[COD_CLIENTE] [varchar] (50) COLLATE Modern_Spanish_CI_AS NULL,
[F_VENCIMIENTO] [smalldatetime] NULL,
[F_VENCIMIENTO2] [smalldatetime] NULL,
[F_ESTANDAR] [smalldatetime] NULL,
[PROCESOS] [varchar] (50) COLLATE Modern_Spanish_CI_AS NULL,
[COMENTARIOS] [varchar] (255) COLLATE Modern_Spanish_CI_AS NULL,
[F_CAPT] [smalldatetime] NULL,
[F_IMPRESION] [smalldatetime] NULL,
[F_GESTION] [smalldatetime] NULL,
[F_CAPT_ASPEL] [smalldatetime] NULL,
[F_CREDITO] [smalldatetime] NULL,
[F_ASIG_RUTA] [smalldatetime] NULL,
[F_LIBERADO] [smalldatetime] NULL,
[F_SURTIDO] [smalldatetime] NULL,
[F_BORDADO] [smalldatetime] NULL,
[F_COSTURA] [smalldatetime] NULL,
[F_CORTE] [smalldatetime] NULL,
[F_ESTAMPADO] [smalldatetime] NULL,
[F_INICIALES] [smalldatetime] NULL,
[F_EMPAQUE] [smalldatetime] NULL,
[F_EMBARQUE] [smalldatetime] NULL,
[FECHAPEDIDO] [smalldatetime] NULL,
[FECHARUTA] [smalldatetime] NULL,
[GUIA] [varchar] (50) COLLATE Modern_Spanish_CI_AS NULL,
[CAJAS] [int] NULL,
[CHOFER] [varchar] (20) COLLATE Modern_Spanish_CI_AS NULL,
[DEPARTAMENTO] [varchar] (50) COLLATE Modern_Spanish_CI_AS NULL,
[DESTINO] [varchar] (30) COLLATE Modern_Spanish_CI_AS NULL,
[OBSERVACIONES] [varchar] (max) COLLATE Modern_Spanish_CI_AS NULL,
[ESTATUS] [varchar] (10) COLLATE Modern_Spanish_CI_AS NULL,
[TRANSPORTE] [varchar] (20) COLLATE Modern_Spanish_CI_AS NULL,
[COM_SURTIDO] [varchar] (255) COLLATE Modern_Spanish_CI_AS NULL,
[COM_BORDADO] [varchar] (255) COLLATE Modern_Spanish_CI_AS NULL,
[COM_COSTURA] [varchar] (255) COLLATE Modern_Spanish_CI_AS NULL,
[COM_CORTE] [varchar] (255) COLLATE Modern_Spanish_CI_AS NULL,
[COM_ESTAMPADO] [varchar] (255) COLLATE Modern_Spanish_CI_AS NULL,
[COM_INICIALES] [varchar] (255) COLLATE Modern_Spanish_CI_AS NULL,
[COM_EMPAQUE] [varchar] (255) COLLATE Modern_Spanish_CI_AS NULL,
[COM_CREDITO] [varchar] (255) COLLATE Modern_Spanish_CI_AS NULL,
[ESTATUS_UPPEDIDOS] [varchar] (1) COLLATE Modern_Spanish_CI_AS NULL,
[F_ENTREGADO] [smalldatetime] NULL,
[COM_ENTREGA] [varchar] (255) COLLATE Modern_Spanish_CI_AS NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[LogUPPedidos] ADD CONSTRAINT [PK_UPPEDIDOS] PRIMARY KEY CLUSTERED  ([UID]) ON [PRIMARY]
GO
