CREATE TABLE [dbo].[_AUDIT_PAR_COMPO01]
(
[UID] [int] NOT NULL IDENTITY(1, 1),
[CREATED_DATE] [datetime] NULL,
[APPLICATION_NAME] [varchar] (255) COLLATE Modern_Spanish_CI_AS NULL,
[TRAN_TYPE] [varchar] (50) COLLATE Modern_Spanish_CI_AS NULL,
[TABLE_TYPE] [varchar] (50) COLLATE Modern_Spanish_CI_AS NULL,
[CVE_DOC] [varchar] (20) COLLATE Modern_Spanish_CI_AS NULL,
[NUM_PAR] [int] NULL,
[CVE_ART] [varchar] (16) COLLATE Modern_Spanish_CI_AS NULL,
[CANT] [float] NULL CONSTRAINT [DF__AUDIT_PAR_COMPO01_CANT] DEFAULT ((0)),
[PXR] [float] NULL CONSTRAINT [DF__AUDIT_PAR_COMPO01_PXR] DEFAULT ((0)),
[GUID] [uniqueidentifier] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[_AUDIT_PAR_COMPO01] ADD CONSTRAINT [PK__AUDIT_PAR_COMPO01] PRIMARY KEY CLUSTERED  ([UID]) ON [PRIMARY]
GO
