//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ulp_dl.aspel_sae80
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACOMP01
    {
        public int CVE_ACOMP { get; set; }
        public Nullable<double> CVTA_COM { get; set; }
        public Nullable<double> CDESCTO { get; set; }
        public Nullable<double> CDES_FIN { get; set; }
        public Nullable<double> CIMP { get; set; }
        public Nullable<double> CTOT_IND { get; set; }
        public Nullable<double> RVTA_COM { get; set; }
        public Nullable<double> RDESCTO { get; set; }
        public Nullable<double> RDES_FIN { get; set; }
        public Nullable<double> RIMP { get; set; }
        public Nullable<double> RTOT_IND { get; set; }
        public Nullable<double> OVTA_COM { get; set; }
        public Nullable<double> ODESCTO { get; set; }
        public Nullable<double> ODES_FIN { get; set; }
        public Nullable<double> OIMP { get; set; }
        public Nullable<double> QVTA_COM { get; set; }
        public Nullable<double> QDESCTO { get; set; }
        public Nullable<double> QDES_FIN { get; set; }
        public Nullable<double> QIMP { get; set; }
        public Nullable<double> DVTA_COM { get; set; }
        public Nullable<double> DDESCTO { get; set; }
        public Nullable<double> DDES_FIN { get; set; }
        public Nullable<double> DIMP { get; set; }
        public Nullable<double> DTOT_IND { get; set; }
        public Nullable<System.DateTime> PER_ACUM { get; set; }
    }
}
