//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ulp_dl.aspel_sae80
{
    using System;
    using System.Collections.Generic;
    
    public partial class AFACT01
    {
        public int CVE_AFACT { get; set; }
        public Nullable<double> FVTA_COM { get; set; }
        public Nullable<double> FDESCTO { get; set; }
        public Nullable<double> FDES_FIN { get; set; }
        public Nullable<double> FIMP { get; set; }
        public Nullable<double> FCOMI { get; set; }
        public Nullable<double> RVTA_COM { get; set; }
        public Nullable<double> RDESCTO { get; set; }
        public Nullable<double> RDES_FIN { get; set; }
        public Nullable<double> RIMP { get; set; }
        public Nullable<double> RCOMI { get; set; }
        public Nullable<double> DVTA_COM { get; set; }
        public Nullable<double> DDESCTO { get; set; }
        public Nullable<double> DDES_FIN { get; set; }
        public Nullable<double> DIMP { get; set; }
        public Nullable<double> DCOMI { get; set; }
        public Nullable<double> PVTA_COM { get; set; }
        public Nullable<double> PDESCTO { get; set; }
        public Nullable<double> PDES_FIN { get; set; }
        public Nullable<double> PIMP { get; set; }
        public Nullable<double> PCOMI { get; set; }
        public Nullable<double> CVTA_COM { get; set; }
        public Nullable<double> CDESCTO { get; set; }
        public Nullable<double> CDES_FIN { get; set; }
        public Nullable<double> CIMP { get; set; }
        public Nullable<double> CCOMI { get; set; }
        public Nullable<double> VVTA_COM { get; set; }
        public Nullable<double> VDESCTO { get; set; }
        public Nullable<double> VDES_FIN { get; set; }
        public Nullable<double> VIMP { get; set; }
        public Nullable<double> VCOMI { get; set; }
        public Nullable<double> WVTA_COM { get; set; }
        public Nullable<double> WDESCTO { get; set; }
        public Nullable<double> WDES_FIN { get; set; }
        public Nullable<double> WIMP { get; set; }
        public Nullable<double> WCOMI { get; set; }
        public Nullable<System.DateTime> PER_ACUM { get; set; }
        public Nullable<double> EVTA_COM { get; set; }
        public Nullable<double> EDESCTO { get; set; }
        public Nullable<double> EDES_FIN { get; set; }
        public Nullable<double> EIMP { get; set; }
        public Nullable<double> ECOMI { get; set; }
    }
}
