//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ulp_dl.aspel_sae80
{
    using System;
    using System.Collections.Generic;
    
    public partial class ALERTA01
    {
        public int CVE_ALERTA { get; set; }
        public string MENSAJE { get; set; }
        public int CANT_DOC { get; set; }
    }
}
