//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ulp_dl.aspel_sae80
{
    using System;
    using System.Collections.Generic;
    
    public partial class ALMACENES01
    {
        public int CVE_ALM { get; set; }
        public string DESCR { get; set; }
        public string DIRECCION { get; set; }
        public string ENCARGADO { get; set; }
        public string TELEFONO { get; set; }
        public Nullable<int> LISTA_PREC { get; set; }
        public string CUEN_CONT { get; set; }
        public Nullable<int> CVE_MENT { get; set; }
        public Nullable<int> CVE_MSAL { get; set; }
        public string STATUS { get; set; }
        public Nullable<double> LAT { get; set; }
        public Nullable<double> LON { get; set; }
        public string UUID { get; set; }
        public Nullable<System.DateTime> VERSION_SINC { get; set; }
        public string UBI_DEST { get; set; }
    }
}
