//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ulp_dl.aspel_sae80
{
    using System;
    using System.Collections.Generic;
    
    public partial class APP_PROSPECT_DOCTOS
    {
        public string TIP_DOC { get; set; }
        public int CVE_DOC { get; set; }
        public string T_DOCTO { get; set; }
        public string TP_DOCTO { get; set; }
        public int CVE_PROS { get; set; }
        public System.DateTime FCH_EMI { get; set; }
        public string CVE_VEND { get; set; }
        public string STATUS { get; set; }
        public string REQ_AUT { get; set; }
        public Nullable<int> CVE_OBS { get; set; }
        public decimal DESC_FIN { get; set; }
        public string TITULO { get; set; }
        public string CONTACTO { get; set; }
        public string PUESTO { get; set; }
        public string CONDICION_PAGO { get; set; }
        public string DESPEDIDA { get; set; }
        public string ENTREGA { get; set; }
        public string SALUDO { get; set; }
        public string TP_ENTREGA { get; set; }
        public string VIGENCIA { get; set; }
        public string NOTI_EMAIL { get; set; }
        public string NOTI_EMAIL_C { get; set; }
        public string NOTI_ASUNTO { get; set; }
        public string NOTI_CUERPO { get; set; }
        public string DSGLSPRCSS { get; set; }
    }
}
