//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ulp_dl.aspel_sae80
{
    using System;
    using System.Collections.Generic;
    
    public partial class APP_PROSPECT_USUARIOS
    {
        public string USUARIO { get; set; }
        public string PASS { get; set; }
        public string STS { get; set; }
        public string NOMBRE { get; set; }
        public string EMAIL { get; set; }
        public string TIPO { get; set; }
        public string COLOR { get; set; }
    }
}
