//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ulp_dl.aspel_sae80
{
    using System;
    using System.Collections.Generic;
    
    public partial class APP_PROSPECT_PROSPECTOS
    {
        public int CVE_PROS { get; set; }
        public string STATUS { get; set; }
        public string CVE_SAE { get; set; }
        public string NOMBRE { get; set; }
        public string RFC { get; set; }
        public string CALLE { get; set; }
        public string NUMINT { get; set; }
        public string NUMEXT { get; set; }
        public string COLONIA { get; set; }
        public string CODIGO { get; set; }
        public string LOCALIDAD { get; set; }
        public string MUNICIPIO { get; set; }
        public string ESTADO { get; set; }
        public string PAIS { get; set; }
        public string GLMAPS { get; set; }
        public string COMPARATIV { get; set; }
        public string GIRO { get; set; }
        public Nullable<int> NUM_EMP { get; set; }
        public string TELEFONO { get; set; }
        public string FAX { get; set; }
        public string PLANO_ROJI { get; set; }
        public string NIV_COMP { get; set; }
        public string CVE_VEND { get; set; }
        public Nullable<int> OBSERV { get; set; }
        public Nullable<System.DateTime> F_VISITA { get; set; }
        public string IND_COMP { get; set; }
        public string S_CORP { get; set; }
        public string FUENTE { get; set; }
        public string FTE_ANT { get; set; }
        public Nullable<System.DateTime> F_REV { get; set; }
        public Nullable<System.DateTime> F_COMPRA { get; set; }
        public Nullable<System.DateTime> F_ASIGNA { get; set; }
        public string ATIENDE { get; set; }
    }
}
