//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ulp_dl.aspel_sae80
{
    using System;
    using System.Collections.Generic;
    
    public partial class APP_PROSPECT_AGENDA
    {
        public string ID { get; set; }
        public string STATUS { get; set; }
        public string GENERO { get; set; }
        public System.DateTime FCH_ALTA { get; set; }
        public System.DateTime FCH_INI { get; set; }
        public System.DateTime FCH_FIN { get; set; }
        public bool ALLDAY { get; set; }
        public int PROSPECTO { get; set; }
        public string TITULO { get; set; }
        public string DIRECCION { get; set; }
        public string CONTACTO { get; set; }
        public string VENDEDOR { get; set; }
        public string DETALLES { get; set; }
        public string LEIDO { get; set; }
        public string RESP_VEND { get; set; }
        public string EDITO { get; set; }
        public Nullable<System.DateTime> FCH_EDI { get; set; }
        public Nullable<System.DateTime> FCH_BAJA { get; set; }
        public string MARCO_BAJA { get; set; }
        public Nullable<int> SEQUENCE { get; set; }
        public Nullable<System.DateTime> FCH_RESP_VEND { get; set; }
    }
}
