//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ulp_dl.aspel_sae80
{
    using System;
    using System.Collections.Generic;
    
    public partial class APP_PROSPECT_DOCTOS_DETALLE
    {
        public string TIP_DOC { get; set; }
        public int CVE_DOC { get; set; }
        public int NUM_PAR { get; set; }
        public string CVE_ART { get; set; }
        public Nullable<decimal> CANT { get; set; }
        public Nullable<decimal> PREC { get; set; }
        public Nullable<decimal> PORC_DESC { get; set; }
        public string IMPU1 { get; set; }
        public string IMPU2 { get; set; }
        public Nullable<int> OBSER { get; set; }
    }
}
