//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ulp_dl.aspel_sae80
{
    using System;
    using System.Collections.Generic;
    
    public partial class APP_PROSPECT_DOCTOS_DETALLE_PROCESOS
    {
        public string TIP_DOC { get; set; }
        public int CVE_DOC { get; set; }
        public int NUM_PAR { get; set; }
        public int NUM_PROC { get; set; }
        public string PROCE { get; set; }
        public string OBS { get; set; }
        public decimal PREC_UNI { get; set; }
    }
}
