//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ulp_dl.aspel_sae80
{
    using System;
    using System.Collections.Generic;
    
    public partial class APP_PROSPECT_ENCUESTAS
    {
        public string ID_ENC { get; set; }
        public string TIPO { get; set; }
        public int CVE_PROS { get; set; }
        public System.DateTime FCH_ENC { get; set; }
        public decimal RST_GBL { get; set; }
        public string USR { get; set; }
        public string COMENTARIOS { get; set; }
    }
}
