//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ulp_dl.aspel_sae80
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AspelSae80Context : DbContext
    {
        public AspelSae80Context()
            : base("name=AspelSae80Context")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ACOMP01> ACOMP01 { get; set; }
        public DbSet<ACTCAM01> ACTCAM01 { get; set; }
        public DbSet<ACTIVI01> ACTIVI01 { get; set; }
        public DbSet<ACUMINVEALM5> ACUMINVEALM5 { get; set; }
        public DbSet<AFACT01> AFACT01 { get; set; }
        public DbSet<ALERTA_USUARIO01> ALERTA_USUARIO01 { get; set; }
        public DbSet<ALERTA01> ALERTA01 { get; set; }
        public DbSet<ALMACENES01> ALMACENES01 { get; set; }
        public DbSet<APP_PROSPECT_AGENDA> APP_PROSPECT_AGENDA { get; set; }
        public DbSet<APP_PROSPECT_DOCTOS> APP_PROSPECT_DOCTOS { get; set; }
        public DbSet<APP_PROSPECT_DOCTOS_DETALLE> APP_PROSPECT_DOCTOS_DETALLE { get; set; }
        public DbSet<APP_PROSPECT_DOCTOS_DETALLE_PROCESOS> APP_PROSPECT_DOCTOS_DETALLE_PROCESOS { get; set; }
        public DbSet<APP_PROSPECT_DOCTOS_OBS> APP_PROSPECT_DOCTOS_OBS { get; set; }
        public DbSet<APP_PROSPECT_ENCUESTAS> APP_PROSPECT_ENCUESTAS { get; set; }
        public DbSet<APP_PROSPECT_ENCUESTAS_DETALLE> APP_PROSPECT_ENCUESTAS_DETALLE { get; set; }
        public DbSet<APP_PROSPECT_PROSPECTOS> APP_PROSPECT_PROSPECTOS { get; set; }
        public DbSet<APP_PROSPECT_PROSPECTOS_OBS> APP_PROSPECT_PROSPECTOS_OBS { get; set; }
        public DbSet<APP_PROSPECT_PROSPECTOS_ORI> APP_PROSPECT_PROSPECTOS_ORI { get; set; }
        public DbSet<APP_PROSPECT_USUARIOS> APP_PROSPECT_USUARIOS { get; set; }
        public DbSet<AUTORIZAC01> AUTORIZAC01 { get; set; }
        public DbSet<AUTORIZAP01> AUTORIZAP01 { get; set; }
        public DbSet<BITA01> BITA01 { get; set; }
        public DbSet<CAMP01> CAMP01 { get; set; }
        public DbSet<CAMPFIL01> CAMPFIL01 { get; set; }
        public DbSet<CAPAS_X_MOV01> CAPAS_X_MOV01 { get; set; }
        public DbSet<CARTAPORTE01> CARTAPORTE01 { get; set; }
        public DbSet<CARTERA> CARTERA { get; set; }
        public DbSet<CFDI_REL01> CFDI_REL01 { get; set; }
        public DbSet<CFDI01> CFDI01 { get; set; }
        public DbSet<CFDIC01> CFDIC01 { get; set; }
        public DbSet<CFDV22> CFDV22 { get; set; }
        public DbSet<CFDV22TMP> CFDV22TMP { get; set; }
        public DbSet<CFGLIN01> CFGLIN01 { get; set; }
        public DbSet<CITAS01> CITAS01 { get; set; }
        public DbSet<CLICAM01> CLICAM01 { get; set; }
        public DbSet<CLIE_CLIB01> CLIE_CLIB01 { get; set; }
        public DbSet<CLIE_TIENDA01> CLIE_TIENDA01 { get; set; }
        public DbSet<CLIE01> CLIE01 { get; set; }
        public DbSet<CLIN01> CLIN01 { get; set; }
        public DbSet<CMT_DET> CMT_DET { get; set; }
        public DbSet<CNSEST01> CNSEST01 { get; set; }
        public DbSet<COLOR01> COLOR01 { get; set; }
        public DbSet<COMPC_CLIB01> COMPC_CLIB01 { get; set; }
        public DbSet<COMPC01> COMPC01 { get; set; }
        public DbSet<COMPD_CLIB01> COMPD_CLIB01 { get; set; }
        public DbSet<COMPD01> COMPD01 { get; set; }
        public DbSet<COMPO_CLIB01> COMPO_CLIB01 { get; set; }
        public DbSet<COMPO01> COMPO01 { get; set; }
        public DbSet<COMPQ_CLIB01> COMPQ_CLIB01 { get; set; }
        public DbSet<COMPQ01> COMPQ01 { get; set; }
        public DbSet<COMPR_CLIB01> COMPR_CLIB01 { get; set; }
        public DbSet<COMPR01> COMPR01 { get; set; }
        public DbSet<CONC01> CONC01 { get; set; }
        public DbSet<CONFIG_ENVIOS01> CONFIG_ENVIOS01 { get; set; }
        public DbSet<CONM01> CONM01 { get; set; }
        public DbSet<CONP01> CONP01 { get; set; }
        public DbSet<CONS_PER01> CONS_PER01 { get; set; }
        public DbSet<CONTAC01> CONTAC01 { get; set; }
        public DbSet<CONTAP01> CONTAP01 { get; set; }
        public DbSet<COSTO_BORDADO> COSTO_BORDADO { get; set; }
        public DbSet<CSTDPEDI> CSTDPEDI { get; set; }
        public DbSet<CTAESQ01> CTAESQ01 { get; set; }
        public DbSet<CTRL_ELIMINA01> CTRL_ELIMINA01 { get; set; }
        public DbSet<CTRLBLOQUEO01> CTRLBLOQUEO01 { get; set; }
        public DbSet<CUEN_DET01> CUEN_DET01 { get; set; }
        public DbSet<CUEN_M01> CUEN_M01 { get; set; }
        public DbSet<CVES_ALTER01> CVES_ALTER01 { get; set; }
        public DbSet<DESACT01> DESACT01 { get; set; }
        public DbSet<DESEMBYAREA> DESEMBYAREA { get; set; }
        public DbSet<DIASFESTIVOS> DIASFESTIVOS { get; set; }
        public DbSet<DOCTOSIGC01> DOCTOSIGC01 { get; set; }
        public DbSet<DOCTOSIGF01> DOCTOSIGF01 { get; set; }
        public DbSet<ENLACE_LTPD01> ENLACE_LTPD01 { get; set; }
        public DbSet<ESTDPEDI> ESTDPEDI { get; set; }
        public DbSet<FACTA_CLIB01> FACTA_CLIB01 { get; set; }
        public DbSet<FACTA01> FACTA01 { get; set; }
        public DbSet<FACTC_CLIB01> FACTC_CLIB01 { get; set; }
        public DbSet<FACTC01> FACTC01 { get; set; }
        public DbSet<FACTD_CLIB01> FACTD_CLIB01 { get; set; }
        public DbSet<FACTD01> FACTD01 { get; set; }
        public DbSet<FACTE_CLIB01> FACTE_CLIB01 { get; set; }
        public DbSet<FACTE01> FACTE01 { get; set; }
        public DbSet<FACTF_CLIB01> FACTF_CLIB01 { get; set; }
        public DbSet<FACTF01> FACTF01 { get; set; }
        public DbSet<FACTG_CLIB01> FACTG_CLIB01 { get; set; }
        public DbSet<FACTG01> FACTG01 { get; set; }
        public DbSet<FACTP_CLIB01> FACTP_CLIB01 { get; set; }
        public DbSet<FACTP01> FACTP01 { get; set; }
        public DbSet<FACTR_CLIB01> FACTR_CLIB01 { get; set; }
        public DbSet<FACTR01> FACTR01 { get; set; }
        public DbSet<FACTT_CLIB01> FACTT_CLIB01 { get; set; }
        public DbSet<FACTT01> FACTT01 { get; set; }
        public DbSet<FACTV_CLIB01> FACTV_CLIB01 { get; set; }
        public DbSet<FACTV01> FACTV01 { get; set; }
        public DbSet<FLET_ENLA> FLET_ENLA { get; set; }
        public DbSet<FLET_MSTR> FLET_MSTR { get; set; }
        public DbSet<FOLCXC01> FOLCXC01 { get; set; }
        public DbSet<FOLCXP01> FOLCXP01 { get; set; }
        public DbSet<FOLIOSC01> FOLIOSC01 { get; set; }
        public DbSet<FOLIOSCXC01> FOLIOSCXC01 { get; set; }
        public DbSet<FOLIOSCXP01> FOLIOSCXP01 { get; set; }
        public DbSet<FOLIOSF01> FOLIOSF01 { get; set; }
        public DbSet<FOTO_INVE01> FOTO_INVE01 { get; set; }
        public DbSet<FUNCIONES_USUARIO> FUNCIONES_USUARIO { get; set; }
        public DbSet<GUICAM01> GUICAM01 { get; set; }
        public DbSet<HNUMSER01> HNUMSER01 { get; set; }
        public DbSet<IMAGENES> IMAGENES { get; set; }
        public DbSet<IMG_ARTICULO01> IMG_ARTICULO01 { get; set; }
        public DbSet<IMPU01> IMPU01 { get; set; }
        public DbSet<INFCLI01> INFCLI01 { get; set; }
        public DbSet<INFENVIO01> INFENVIO01 { get; set; }
        public DbSet<INTCOI01> INTCOI01 { get; set; }
        public DbSet<INTERFAZ_PLUS_CTRL_ENLACE_COMPRAS> INTERFAZ_PLUS_CTRL_ENLACE_COMPRAS { get; set; }
        public DbSet<INVE_AMAZON01> INVE_AMAZON01 { get; set; }
        public DbSet<INVE_CLIB01> INVE_CLIB01 { get; set; }
        public DbSet<INVE01> INVE01 { get; set; }
        public DbSet<INVEN_CLARO01> INVEN_CLARO01 { get; set; }
        public DbSet<INVENTARIO> INVENTARIO { get; set; }
        public DbSet<INVFIS01> INVFIS01 { get; set; }
        public DbSet<ISIP_BITACORA> ISIP_BITACORA { get; set; }
        public DbSet<ISIP_FACT_ANT_CTRL> ISIP_FACT_ANT_CTRL { get; set; }
        public DbSet<ISIP_MONITOR_FACT_ANT> ISIP_MONITOR_FACT_ANT { get; set; }
        public DbSet<ISIP_NAMESPACES> ISIP_NAMESPACES { get; set; }
        public DbSet<ISIP_PERMISOS> ISIP_PERMISOS { get; set; }
        public DbSet<ISIP_TRANSFERENCIAS_APARTADO> ISIP_TRANSFERENCIAS_APARTADO { get; set; }
        public DbSet<ISIP_TRANSFERENCIAS_VIRTUALES> ISIP_TRANSFERENCIAS_VIRTUALES { get; set; }
        public DbSet<KITS01> KITS01 { get; set; }
        public DbSet<LISTPRODSUST01> LISTPRODSUST01 { get; set; }
        public DbSet<LNKOLKC01> LNKOLKC01 { get; set; }
        public DbSet<LNKOLKP01> LNKOLKP01 { get; set; }
        public DbSet<LTPD01> LTPD01 { get; set; }
        public DbSet<MINVE01> MINVE01 { get; set; }
        public DbSet<MONED01> MONED01 { get; set; }
        public DbSet<MULT01> MULT01 { get; set; }
        public DbSet<NUMSER01> NUMSER01 { get; set; }
        public DbSet<OBS_DOCC01> OBS_DOCC01 { get; set; }
        public DbSet<OBS_DOCF01> OBS_DOCF01 { get; set; }
        public DbSet<OCLI01> OCLI01 { get; set; }
        public DbSet<OCUEN01> OCUEN01 { get; set; }
        public DbSet<OINVE01> OINVE01 { get; set; }
        public DbSet<OLTPD01> OLTPD01 { get; set; }
        public DbSet<OMINVE01> OMINVE01 { get; set; }
        public DbSet<OPAGA01> OPAGA01 { get; set; }
        public DbSet<OPER_TERCEROS01> OPER_TERCEROS01 { get; set; }
        public DbSet<OPER_X_TIPO_TERCERO01> OPER_X_TIPO_TERCERO01 { get; set; }
        public DbSet<OPERADOR01> OPERADOR01 { get; set; }
        public DbSet<OPROV01> OPROV01 { get; set; }
        public DbSet<PAGA_DET01> PAGA_DET01 { get; set; }
        public DbSet<PAGA_M01> PAGA_M01 { get; set; }
        public DbSet<PAGOCODI01> PAGOCODI01 { get; set; }
        public DbSet<PAGOLINEA01> PAGOLINEA01 { get; set; }
        public DbSet<PAGOS_PED_TIENDA01> PAGOS_PED_TIENDA01 { get; set; }
        public DbSet<PAIS01> PAIS01 { get; set; }
        public DbSet<PAR_COMPC_CLIB01> PAR_COMPC_CLIB01 { get; set; }
        public DbSet<PAR_COMPC01> PAR_COMPC01 { get; set; }
        public DbSet<PAR_COMPD_CLIB01> PAR_COMPD_CLIB01 { get; set; }
        public DbSet<PAR_COMPD01> PAR_COMPD01 { get; set; }
        public DbSet<PAR_COMPO_CLIB01> PAR_COMPO_CLIB01 { get; set; }
        public DbSet<PAR_COMPO01> PAR_COMPO01 { get; set; }
        public DbSet<PAR_COMPQ_CLIB01> PAR_COMPQ_CLIB01 { get; set; }
        public DbSet<PAR_COMPQ01> PAR_COMPQ01 { get; set; }
        public DbSet<PAR_COMPR_CLIB01> PAR_COMPR_CLIB01 { get; set; }
        public DbSet<PAR_COMPR01> PAR_COMPR01 { get; set; }
        public DbSet<PAR_FACTA_CLIB01> PAR_FACTA_CLIB01 { get; set; }
        public DbSet<PAR_FACTA01> PAR_FACTA01 { get; set; }
        public DbSet<PAR_FACTC_CLIB01> PAR_FACTC_CLIB01 { get; set; }
        public DbSet<PAR_FACTC01> PAR_FACTC01 { get; set; }
        public DbSet<PAR_FACTD_CLIB01> PAR_FACTD_CLIB01 { get; set; }
        public DbSet<PAR_FACTD01> PAR_FACTD01 { get; set; }
        public DbSet<PAR_FACTE_CLIB01> PAR_FACTE_CLIB01 { get; set; }
        public DbSet<PAR_FACTE01> PAR_FACTE01 { get; set; }
        public DbSet<PAR_FACTF_CLIB01> PAR_FACTF_CLIB01 { get; set; }
        public DbSet<PAR_FACTF01> PAR_FACTF01 { get; set; }
        public DbSet<PAR_FACTG_CLIB01> PAR_FACTG_CLIB01 { get; set; }
        public DbSet<PAR_FACTG01> PAR_FACTG01 { get; set; }
        public DbSet<PAR_FACTP_CLIB01> PAR_FACTP_CLIB01 { get; set; }
        public DbSet<PAR_FACTP01> PAR_FACTP01 { get; set; }
        public DbSet<PAR_FACTR_CLIB01> PAR_FACTR_CLIB01 { get; set; }
        public DbSet<PAR_FACTR01> PAR_FACTR01 { get; set; }
        public DbSet<PAR_FACTT_CLIB01> PAR_FACTT_CLIB01 { get; set; }
        public DbSet<PAR_FACTT01> PAR_FACTT01 { get; set; }
        public DbSet<PAR_FACTV_CLIB01> PAR_FACTV_CLIB01 { get; set; }
        public DbSet<PAR_FACTV01> PAR_FACTV01 { get; set; }
        public DbSet<PAR_PED_AMAZON01> PAR_PED_AMAZON01 { get; set; }
        public DbSet<PAR_PED_CLARO01> PAR_PED_CLARO01 { get; set; }
        public DbSet<PAR_PED_TIEND01> PAR_PED_TIEND01 { get; set; }
        public DbSet<PARAM_APLICASOC01> PARAM_APLICASOC01 { get; set; }
        public DbSet<PARAM_CAMPOSLIBRES01> PARAM_CAMPOSLIBRES01 { get; set; }
        public DbSet<PARAM_CLIENTES01> PARAM_CLIENTES01 { get; set; }
        public DbSet<PARAM_CODI01> PARAM_CODI01 { get; set; }
        public DbSet<PARAM_COMPRAS01> PARAM_COMPRAS01 { get; set; }
        public DbSet<PARAM_CTACONTABLE01> PARAM_CTACONTABLE01 { get; set; }
        public DbSet<PARAM_DATOSBANCARIOS01> PARAM_DATOSBANCARIOS01 { get; set; }
        public DbSet<PARAM_DATOSBD01> PARAM_DATOSBD01 { get; set; }
        public DbSet<PARAM_DATOSEMP01> PARAM_DATOSEMP01 { get; set; }
        public DbSet<PARAM_DATOSGRALES01> PARAM_DATOSGRALES01 { get; set; }
        public DbSet<PARAM_DOMEXPED01> PARAM_DOMEXPED01 { get; set; }
        public DbSet<PARAM_DOMFISCAL01> PARAM_DOMFISCAL01 { get; set; }
        public DbSet<PARAM_FACTURA01> PARAM_FACTURA01 { get; set; }
        public DbSet<PARAM_FACTURAELECTRONICA01> PARAM_FACTURAELECTRONICA01 { get; set; }
        public DbSet<PARAM_FOLIOSC01> PARAM_FOLIOSC01 { get; set; }
        public DbSet<PARAM_FOLIOSF01> PARAM_FOLIOSF01 { get; set; }
        public DbSet<PARAM_GRAFICAS01> PARAM_GRAFICAS01 { get; set; }
        public DbSet<PARAM_INVENTARIO01> PARAM_INVENTARIO01 { get; set; }
        public DbSet<PARAM_PARTIDASCOMP01> PARAM_PARTIDASCOMP01 { get; set; }
        public DbSet<PARAM_PARTIDASFACT01> PARAM_PARTIDASFACT01 { get; set; }
        public DbSet<PARAM_PROVEEDORES01> PARAM_PROVEEDORES01 { get; set; }
        public DbSet<PARAM_TIENDAS01> PARAM_TIENDAS01 { get; set; }
        public DbSet<PARAM_TIPODOCTOSC01> PARAM_TIPODOCTOSC01 { get; set; }
        public DbSet<PARAM_TIPODOCTOSF01> PARAM_TIPODOCTOSF01 { get; set; }
        public DbSet<PED_AMAZON01> PED_AMAZON01 { get; set; }
        public DbSet<PED_CLARO01> PED_CLARO01 { get; set; }
        public DbSet<PED_DET> PED_DET { get; set; }
        public DbSet<PED_MSTR> PED_MSTR { get; set; }
        public DbSet<PED_TEMP> PED_TEMP { get; set; }
        public DbSet<PED_TIEND01> PED_TIEND01 { get; set; }
        public DbSet<PERIODOS01> PERIODOS01 { get; set; }
        public DbSet<POLI01> POLI01 { get; set; }
        public DbSet<PRECIO_X_CONF01> PRECIO_X_CONF01 { get; set; }
        public DbSet<PRECIO_X_PROD01> PRECIO_X_PROD01 { get; set; }
        public DbSet<PRECIOS01> PRECIOS01 { get; set; }
        public DbSet<PRIORIDAD_MAQUILA> PRIORIDAD_MAQUILA { get; set; }
        public DbSet<PROD_CIERREORDEN01> PROD_CIERREORDEN01 { get; set; }
        public DbSet<PROD_CONFIGBD01> PROD_CONFIGBD01 { get; set; }
        public DbSet<PROD_ENTRADAFAB01> PROD_ENTRADAFAB01 { get; set; }
        public DbSet<PROD_ENTREGAPARCIAL01> PROD_ENTREGAPARCIAL01 { get; set; }
        public DbSet<PROD_ESQINDI01> PROD_ESQINDI01 { get; set; }
        public DbSet<PROD_FABDIRECTA01> PROD_FABDIRECTA01 { get; set; }
        public DbSet<PROD_INSUMOS01> PROD_INSUMOS01 { get; set; }
        public DbSet<PROD_LOTESXCOMP01> PROD_LOTESXCOMP01 { get; set; }
        public DbSet<PROD_MULTIPLANTAS01> PROD_MULTIPLANTAS01 { get; set; }
        public DbSet<PROD_OBSDETPT01> PROD_OBSDETPT01 { get; set; }
        public DbSet<PROD_OBSENTFAB01> PROD_OBSENTFAB01 { get; set; }
        public DbSet<PROD_OBSORD01> PROD_OBSORD01 { get; set; }
        public DbSet<PROD_OBSPT01> PROD_OBSPT01 { get; set; }
        public DbSet<PROD_ORDENES01> PROD_ORDENES01 { get; set; }
        public DbSet<PROD_PARAMSIS01> PROD_PARAMSIS01 { get; set; }
        public DbSet<PROD_PROCESOS01> PROD_PROCESOS01 { get; set; }
        public DbSet<PROD_PRODTERM_DET01> PROD_PRODTERM_DET01 { get; set; }
        public DbSet<PROD_PRODTERM01> PROD_PRODTERM01 { get; set; }
        public DbSet<PROD_REGISTROAUTOM01> PROD_REGISTROAUTOM01 { get; set; }
        public DbSet<PROD_SERIESXCOMP01> PROD_SERIESXCOMP01 { get; set; }
        public DbSet<PROD_SUSTITUTOS01> PROD_SUSTITUTOS01 { get; set; }
        public DbSet<PROD_TBLCONTROL01> PROD_TBLCONTROL01 { get; set; }
        public DbSet<PROD_TIPOINSUMO01> PROD_TIPOINSUMO01 { get; set; }
        public DbSet<PRODSUST01> PRODSUST01 { get; set; }
        public DbSet<PROV_CLIB01> PROV_CLIB01 { get; set; }
        public DbSet<PROV01> PROV01 { get; set; }
        public DbSet<PRVPROD01> PRVPROD01 { get; set; }
        public DbSet<RESACT01> RESACT01 { get; set; }
        public DbSet<RESULT01> RESULT01 { get; set; }
        public DbSet<SOLICITUDES_ESPECIALES> SOLICITUDES_ESPECIALES { get; set; }
        public DbSet<TALLA01> TALLA01 { get; set; }
        public DbSet<TBLCONTROL01> TBLCONTROL01 { get; set; }
        public DbSet<TEMP1_> TEMP1_ { get; set; }
        public DbSet<TIPO_TERCEROS01> TIPO_TERCEROS01 { get; set; }
        public DbSet<UPPEDIDOS> UPPEDIDOS { get; set; }
        public DbSet<USUARIOS> USUARIOS { get; set; }
        public DbSet<VEND01> VEND01 { get; set; }
        public DbSet<ZONA01> ZONA01 { get; set; }
        public DbSet<U_DEPARTAMENTO> U_DEPARTAMENTO { get; set; }
        public DbSet<FACT_GLOBAL01> FACT_GLOBAL01 { get; set; }
    }
}
