//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ulp_dl.aspel_sae80
{
    using System;
    using System.Collections.Generic;
    
    public partial class AUTORIZAC01
    {
        public int CVE_AUT { get; set; }
        public string DOCTO_AUT { get; set; }
        public string NUM_AUT { get; set; }
        public Nullable<int> MES_VENC { get; set; }
        public Nullable<int> ANIO_VENC { get; set; }
    }
}
