//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ulp_dl.aspel_sae80
{
    using System;
    using System.Collections.Generic;
    
    public partial class BITA01
    {
        public int CVE_BITA { get; set; }
        public string CVE_CLIE { get; set; }
        public string CVE_CAMPANIA { get; set; }
        public string CVE_ACTIVIDAD { get; set; }
        public Nullable<System.DateTime> FECHAHORA { get; set; }
        public Nullable<short> CVE_USUARIO { get; set; }
        public string OBSERVACIONES { get; set; }
        public string STATUS { get; set; }
        public string NOM_USUARIO { get; set; }
    }
}
