//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ulp_dl.aspel_sae80
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAMP01
    {
        public string CVE_CAMPANIA { get; set; }
        public string DESCRIP { get; set; }
        public string FILTRAR_AUTO { get; set; }
        public string LEYENDA { get; set; }
        public string STATUS { get; set; }
        public Nullable<System.DateTime> FECHAD { get; set; }
        public Nullable<System.DateTime> FECHAH { get; set; }
        public string ORIGEN { get; set; }
        public string TIPO { get; set; }
    }
}
