//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ulp_dl.aspel_sae80
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAMPFIL01
    {
        public string CVE_CAMPANIA { get; set; }
        public Nullable<int> CMB_VIGENCIA { get; set; }
        public Nullable<int> CRITERIOS_CLIEN { get; set; }
        public string CLIE_DESDE { get; set; }
        public string CLIE_HASTA { get; set; }
        public string CLASIFICACION { get; set; }
        public string VENDEDOR { get; set; }
        public string ZONA { get; set; }
        public string ESTATUS { get; set; }
        public Nullable<int> CMB_VENTA_ANUAL { get; set; }
        public Nullable<double> VENTA_ANUAL { get; set; }
        public Nullable<int> CMB_DESCUENTO { get; set; }
        public Nullable<double> DESCUENTO { get; set; }
        public Nullable<int> CMB_SALDO { get; set; }
        public Nullable<double> SALDO { get; set; }
        public string CHK_LIMITE { get; set; }
        public Nullable<int> CMB_PORCENTAJE_LIM { get; set; }
        public Nullable<int> CMB_DIAS_CARTERA { get; set; }
        public Nullable<int> DIAS { get; set; }
        public Nullable<int> CHK_DIAS { get; set; }
        public Nullable<int> CMB_DIAS_CREDITO { get; set; }
        public Nullable<System.DateTime> FECH_INICIAL_ULTCOMPR { get; set; }
        public Nullable<System.DateTime> FECH_FINAL_ULTCOMPR { get; set; }
        public Nullable<int> CMB_ULTIMACOMPRA { get; set; }
        public Nullable<System.DateTime> FECH_INICIAL_APLIC { get; set; }
        public Nullable<System.DateTime> FECH_FINAL_APLIC { get; set; }
        public Nullable<int> CMB_APLIC { get; set; }
        public string DOCS_DESDE { get; set; }
        public string DOCS_HASTA { get; set; }
        public string FOLIOS_DESDE { get; set; }
        public string FOLIOS_HASTA { get; set; }
        public string CONCEPTOS { get; set; }
        public string PERIODO { get; set; }
        public Nullable<System.DateTime> FECH_PERIODO_INICIAL { get; set; }
        public Nullable<System.DateTime> FECH_PERIODO_FINAL { get; set; }
        public Nullable<int> CMB_PERIODO { get; set; }
        public Nullable<int> TIPOVENTA { get; set; }
        public string VENTAS_DESDE { get; set; }
        public string VENTAS_HASTA { get; set; }
        public string VENTAS_VENDEDOR { get; set; }
        public string VENTAS_MONEDA { get; set; }
        public string VENTAS_ALMACEN { get; set; }
        public Nullable<System.DateTime> VENTAS_FECH_INICIAL { get; set; }
        public Nullable<System.DateTime> VENTAS_FECH_FINAL { get; set; }
        public Nullable<int> CMB_VENTAS { get; set; }
        public string CHK_CANCELACIONES { get; set; }
        public Nullable<int> CMB_IMPORTE_VENTA { get; set; }
        public Nullable<double> IMPORTE_VENTA { get; set; }
        public string PROD_DESDE { get; set; }
        public string PROD_HASTA { get; set; }
        public string PROD_LINEA { get; set; }
        public string INV_PROD { get; set; }
        public string INV_GRUPOP { get; set; }
        public string INV_KITS { get; set; }
        public string INV_SERV { get; set; }
        public Nullable<int> CMB_CANTIDAD { get; set; }
        public Nullable<double> INV_CANT { get; set; }
        public string GUIA { get; set; }
    }
}
