//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ulp_dl.aspel_sae80
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAPAS_X_MOV01
    {
        public string CVE_ART { get; set; }
        public int NUM_MOV { get; set; }
        public int NUM_MOV_AFT { get; set; }
        public Nullable<double> CANT_AFT { get; set; }
        public Nullable<double> COSTO_AFT { get; set; }
    }
}
