//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ulp_dl.aspel_sae80
{
    using System;
    using System.Collections.Generic;
    
    public partial class CARTERA
    {
        public int ID { get; set; }
        public string CLIENTE { get; set; }
        public int ANNIO { get; set; }
        public string MES1 { get; set; }
        public string MES2 { get; set; }
        public string MES3 { get; set; }
        public string MES4 { get; set; }
        public string MES5 { get; set; }
        public string MES6 { get; set; }
        public string MES7 { get; set; }
        public string MES8 { get; set; }
        public string MES9 { get; set; }
        public string MES10 { get; set; }
        public string MES11 { get; set; }
        public string MES12 { get; set; }
        public Nullable<double> TOTAL { get; set; }
    }
}
