//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ulp_dl.aspel_sae80
{
    using System;
    using System.Collections.Generic;
    
    public partial class CFDI_REL01
    {
        public string UUID { get; set; }
        public string TIP_REL { get; set; }
        public string CVE_DOC { get; set; }
        public string CVE_DOC_REL { get; set; }
        public string TIP_DOC { get; set; }
        public string NO_SERIE { get; set; }
        public string FOLIO { get; set; }
        public string FECHA_CERT { get; set; }
    }
}
