//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ulp_dl.aspel_sae80
{
    using System;
    using System.Collections.Generic;
    
    public partial class CFDI01
    {
        public string TIPO_DOC { get; set; }
        public string CVE_DOC { get; set; }
        public string VERSION { get; set; }
        public string UUID { get; set; }
        public string NO_SERIE { get; set; }
        public string FECHA_CERT { get; set; }
        public string FECHA_CANCELA { get; set; }
        public string XML_DOC { get; set; }
        public string XML_DOC_CANCELA { get; set; }
        public string DESGLOCEIMP1 { get; set; }
        public string DESGLOCEIMP2 { get; set; }
        public string DESGLOCEIMP3 { get; set; }
        public string DESGLOCEIMP4 { get; set; }
        public string MSJ_CANC { get; set; }
        public string PENDIENTE { get; set; }
        public Nullable<int> CVE_USUARIO { get; set; }
        public string MOTIVO_CANC { get; set; }
        public string UUID_REL { get; set; }
    }
}
