//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ulp_dl.aspel_sae80
{
    using System;
    using System.Collections.Generic;
    
    public partial class CFDIC01
    {
        public string TIPO_DOC { get; set; }
        public string CVE_DOC { get; set; }
        public string ID_TIMBRADO { get; set; }
        public string FECHA_TIMBRADO { get; set; }
        public string FOLIO_TIMBRADO { get; set; }
        public string SERIE_TIMBRADO { get; set; }
        public string RFC_EMISOR { get; set; }
        public string RFC_RECEPTOR { get; set; }
        public Nullable<double> MONTO { get; set; }
        public string XML_DOC { get; set; }
        public string RESPUESTA { get; set; }
        public string XML_ACUSE { get; set; }
        public string VERSION { get; set; }
    }
}
