//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ulp_dl.aspel_sae80
{
    using System;
    using System.Collections.Generic;
    
    public partial class CFDV22
    {
        public string TIP_DOC { get; set; }
        public string CVE_DOC { get; set; }
        public string metodoDePago { get; set; }
        public string LugarExpedicion { get; set; }
        public string NumCtaPago { get; set; }
        public string RegimenFiscal { get; set; }
        public string CO { get; set; }
        public string SELLO { get; set; }
    }
}
