//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ulp_dl.aspel_sae80
{
    using System;
    using System.Collections.Generic;
    
    public partial class CFGLIN01
    {
        public string CVE_LIN { get; set; }
        public Nullable<int> LONG1 { get; set; }
        public string SEP1 { get; set; }
        public Nullable<int> LONG2 { get; set; }
        public string SEP2 { get; set; }
        public Nullable<int> LONG3 { get; set; }
    }
}
