//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ulp_dl.aspel_sae80
{
    using System;
    using System.Collections.Generic;
    
    public partial class CITAS01
    {
        public string CVE_CLIE { get; set; }
        public string ASUNTO { get; set; }
        public string ID_OUTLOOK { get; set; }
        public Nullable<System.DateTime> FECHA_HORA { get; set; }
        public string STATUS { get; set; }
        public string USUARIO { get; set; }
        public Nullable<short> CVE_CITA { get; set; }
    }
}
