//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ulp_dl.aspel_sae80
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLICAM01
    {
        public string CVE_CAMPANIA { get; set; }
        public string CVE_CLIE { get; set; }
        public string CVE_ACTIVIDAD { get; set; }
        public string CVE_RESULTADO { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
        public Nullable<int> PRIORIDAD { get; set; }
        public string STATUS { get; set; }
        public string COMENTARIOS { get; set; }
        public Nullable<int> STATUS_ACTIVIDAD { get; set; }
    }
}
