//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ulp_dl.aspel_sae80
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIE01
    {
        public string CLAVE { get; set; }
        public string STATUS { get; set; }
        public string NOMBRE { get; set; }
        public string RFC { get; set; }
        public string CALLE { get; set; }
        public string NUMINT { get; set; }
        public string NUMEXT { get; set; }
        public string CRUZAMIENTOS { get; set; }
        public string CRUZAMIENTOS2 { get; set; }
        public string COLONIA { get; set; }
        public string CODIGO { get; set; }
        public string LOCALIDAD { get; set; }
        public string MUNICIPIO { get; set; }
        public string ESTADO { get; set; }
        public string PAIS { get; set; }
        public string NACIONALIDAD { get; set; }
        public string REFERDIR { get; set; }
        public string TELEFONO { get; set; }
        public string CLASIFIC { get; set; }
        public string FAX { get; set; }
        public string PAG_WEB { get; set; }
        public string CURP { get; set; }
        public string CVE_ZONA { get; set; }
        public string IMPRIR { get; set; }
        public string MAIL { get; set; }
        public Nullable<int> NIVELSEC { get; set; }
        public string ENVIOSILEN { get; set; }
        public string EMAILPRED { get; set; }
        public string DIAREV { get; set; }
        public string DIAPAGO { get; set; }
        public string CON_CREDITO { get; set; }
        public Nullable<int> DIASCRED { get; set; }
        public Nullable<double> LIMCRED { get; set; }
        public Nullable<double> SALDO { get; set; }
        public Nullable<int> LISTA_PREC { get; set; }
        public Nullable<int> CVE_BITA { get; set; }
        public string ULT_PAGOD { get; set; }
        public Nullable<double> ULT_PAGOM { get; set; }
        public Nullable<System.DateTime> ULT_PAGOF { get; set; }
        public Nullable<double> DESCUENTO { get; set; }
        public string ULT_VENTAD { get; set; }
        public Nullable<double> ULT_COMPM { get; set; }
        public Nullable<System.DateTime> FCH_ULTCOM { get; set; }
        public Nullable<double> VENTAS { get; set; }
        public string CVE_VEND { get; set; }
        public Nullable<int> CVE_OBS { get; set; }
        public string TIPO_EMPRESA { get; set; }
        public string MATRIZ { get; set; }
        public string PROSPECTO { get; set; }
        public string CALLE_ENVIO { get; set; }
        public string NUMINT_ENVIO { get; set; }
        public string NUMEXT_ENVIO { get; set; }
        public string CRUZAMIENTOS_ENVIO { get; set; }
        public string CRUZAMIENTOS_ENVIO2 { get; set; }
        public string COLONIA_ENVIO { get; set; }
        public string LOCALIDAD_ENVIO { get; set; }
        public string MUNICIPIO_ENVIO { get; set; }
        public string ESTADO_ENVIO { get; set; }
        public string PAIS_ENVIO { get; set; }
        public string CODIGO_ENVIO { get; set; }
        public string CVE_ZONA_ENVIO { get; set; }
        public string REFERENCIA_ENVIO { get; set; }
        public string CUENTA_CONTABLE { get; set; }
        public string ADDENDAF { get; set; }
        public string ADDENDAD { get; set; }
        public string NAMESPACE { get; set; }
        public string METODODEPAGO { get; set; }
        public string NUMCTAPAGO { get; set; }
        public string MODELO { get; set; }
        public string DES_IMPU1 { get; set; }
        public string DES_IMPU2 { get; set; }
        public string DES_IMPU3 { get; set; }
        public string DES_IMPU4 { get; set; }
        public string DES_PER { get; set; }
        public Nullable<double> LAT_GENERAL { get; set; }
        public Nullable<double> LON_GENERAL { get; set; }
        public Nullable<double> LAT_ENVIO { get; set; }
        public Nullable<double> LON_ENVIO { get; set; }
        public string UUID { get; set; }
        public Nullable<System.DateTime> VERSION_SINC { get; set; }
        public string USO_CFDI { get; set; }
        public string CVE_PAIS_SAT { get; set; }
        public string NUMIDREGFISCAL { get; set; }
        public string FORMADEPAGOSAT { get; set; }
        public string ADDENDAE { get; set; }
        public string ADDENDAG { get; set; }
        public string UBICACION_R { get; set; }
        public string ADDENDAT { get; set; }
        public string NOMBRECOMERCIAL { get; set; }
        public Nullable<int> VAL_RFC { get; set; }
        public string REG_FISC { get; set; }
    }
}
