//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ulp_dl.aspel_sae80
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMT_DET
    {
        public int CMT_PEDIDO { get; set; }
        public int CMT_INDX { get; set; }
        public string CMT_CMMT { get; set; }
        public string CMT_COMO { get; set; }
        public string CMT_DONDE { get; set; }
        public string CMT_AGRUPADOR { get; set; }
        public string CMT_PROCESO { get; set; }
        public Nullable<decimal> CMT_PRE_PROCESO { get; set; }
        public string CMT_MAQUILERO { get; set; }
        public Nullable<System.DateTime> CMT_FECHA { get; set; }
        public string CMT_FACT_MAQUILA { get; set; }
        public string CMT_MODELO { get; set; }
        public string CMT_RUTA { get; set; }
        public string CMT_CLIENTE { get; set; }
        public Nullable<int> CMT_PUNTADAS { get; set; }
        public string CMT_ESTATUS { get; set; }
        public Nullable<int> CMT_CANTIDAD { get; set; }
        public string CMT_DEPARTAMENTO { get; set; }
        public Nullable<int> CMT_ORDENAMIENTO { get; set; }
        public Nullable<System.DateTime> CMT_FVENC { get; set; }
        public string CMT_TIPO { get; set; }
        public Nullable<decimal> CMT_COS_PROCESO { get; set; }
        public Nullable<System.DateTime> CMT_FVENC_EMPAQUE { get; set; }
    }
}
