//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ulp_dl.aspel_sae80
{
    using System;
    using System.Collections.Generic;
    
    public partial class CNSEST01
    {
        public int CVE_ESTAD { get; set; }
        public string TITULO { get; set; }
        public Nullable<short> USUARIO { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
        public string TIPO { get; set; }
        public string ARCHIVO { get; set; }
        public string VER_FILTRO { get; set; }
        public string UUID { get; set; }
        public Nullable<System.DateTime> VERSION_SINC { get; set; }
        public string DISPONIBLE_MOVIL { get; set; }
    }
}
