//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ulp_dl.aspel_sae80
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMPO01
    {
        public string TIP_DOC { get; set; }
        public string CVE_DOC { get; set; }
        public string CVE_CLPV { get; set; }
        public string STATUS { get; set; }
        public string SU_REFER { get; set; }
        public System.DateTime FECHA_DOC { get; set; }
        public Nullable<System.DateTime> FECHA_REC { get; set; }
        public Nullable<System.DateTime> FECHA_PAG { get; set; }
        public Nullable<System.DateTime> FECHA_CANCELA { get; set; }
        public Nullable<double> CAN_TOT { get; set; }
        public Nullable<double> IMP_TOT1 { get; set; }
        public Nullable<double> IMP_TOT2 { get; set; }
        public Nullable<double> IMP_TOT3 { get; set; }
        public Nullable<double> IMP_TOT4 { get; set; }
        public Nullable<double> DES_TOT { get; set; }
        public Nullable<double> DES_FIN { get; set; }
        public Nullable<double> TOT_IND { get; set; }
        public string OBS_COND { get; set; }
        public Nullable<int> CVE_OBS { get; set; }
        public Nullable<int> NUM_ALMA { get; set; }
        public string ACT_CXP { get; set; }
        public string ACT_COI { get; set; }
        public Nullable<int> NUM_MONED { get; set; }
        public Nullable<double> TIPCAMB { get; set; }
        public string ENLAZADO { get; set; }
        public string TIP_DOC_E { get; set; }
        public Nullable<int> NUM_PAGOS { get; set; }
        public Nullable<System.DateTime> FECHAELAB { get; set; }
        public string SERIE { get; set; }
        public Nullable<int> FOLIO { get; set; }
        public Nullable<int> CTLPOL { get; set; }
        public string ESCFD { get; set; }
        public string CONTADO { get; set; }
        public string BLOQ { get; set; }
        public Nullable<double> DES_FIN_PORC { get; set; }
        public Nullable<double> DES_TOT_PORC { get; set; }
        public Nullable<double> IMPORTE { get; set; }
        public string TIP_DOC_ANT { get; set; }
        public string DOC_ANT { get; set; }
        public string TIP_DOC_SIG { get; set; }
        public string DOC_SIG { get; set; }
        public string FORMAENVIO { get; set; }
        public string METODODEPAGO { get; set; }
    }
}
