//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ulp_dl.aspel_sae80
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONC01
    {
        public int NUM_CPTO { get; set; }
        public string DESCR { get; set; }
        public string TIPO { get; set; }
        public string CUEN_CONT { get; set; }
        public string CON_REFER { get; set; }
        public Nullable<int> GEN_CPTO { get; set; }
        public string AUTORIZACION { get; set; }
        public Nullable<short> SIGNO { get; set; }
        public string ES_FMA_PAG { get; set; }
        public Nullable<int> CVE_BITA { get; set; }
        public string STATUS { get; set; }
        public Nullable<short> ENLINEA { get; set; }
        public string DAR_CAMBIO { get; set; }
        public string UUID { get; set; }
        public Nullable<System.DateTime> VERSION_SINC { get; set; }
        public string FORMADEPAGOSAT { get; set; }
        public string CONFIG_CODI { get; set; }
    }
}
