//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ulp_dl.aspel_sae80
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONS_PER01
    {
        public int CVE_CONS { get; set; }
        public string TITULO { get; set; }
        public Nullable<short> USUARIO { get; set; }
        public Nullable<int> TIPO { get; set; }
        public string ARCHIVO { get; set; }
    }
}
