//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ulp_dl.aspel_sae80
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTAESQ01
    {
        public int NUM_IMPU { get; set; }
        public double PORCENTAJE { get; set; }
        public string CUEN_VENT { get; set; }
        public string CUEN_COMP { get; set; }
    }
}
