//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ulp_dl.aspel_sae80
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTRL_ELIMINA01
    {
        public string TABLA { get; set; }
        public string UUID_REG { get; set; }
        public System.DateTime VERSION_SINC { get; set; }
        public string UUID { get; set; }
    }
}
