//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ulp_dl.aspel_sae80
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUEN_DET01
    {
        public string CVE_CLIE { get; set; }
        public string REFER { get; set; }
        public int ID_MOV { get; set; }
        public Nullable<int> NUM_CPTO { get; set; }
        public int NUM_CARGO { get; set; }
        public Nullable<int> CVE_OBS { get; set; }
        public string NO_FACTURA { get; set; }
        public string DOCTO { get; set; }
        public Nullable<double> IMPORTE { get; set; }
        public Nullable<System.DateTime> FECHA_APLI { get; set; }
        public Nullable<System.DateTime> FECHA_VENC { get; set; }
        public string AFEC_COI { get; set; }
        public string STRCVEVEND { get; set; }
        public Nullable<int> NUM_MONED { get; set; }
        public Nullable<double> TCAMBIO { get; set; }
        public Nullable<double> IMPMON_EXT { get; set; }
        public Nullable<System.DateTime> FECHAELAB { get; set; }
        public Nullable<int> CTLPOL { get; set; }
        public string CVE_FOLIO { get; set; }
        public string TIPO_MOV { get; set; }
        public Nullable<int> CVE_BITA { get; set; }
        public Nullable<int> SIGNO { get; set; }
        public Nullable<int> CVE_AUT { get; set; }
        public Nullable<short> USUARIO { get; set; }
        public string OPERACIONPL { get; set; }
        public string REF_SIST { get; set; }
        public int NO_PARTIDA { get; set; }
        public string REFBANCO_ORIGEN { get; set; }
        public string REFBANCO_DEST { get; set; }
        public string NUMCTAPAGO_ORIGEN { get; set; }
        public string NUMCTAPAGO_DESTINO { get; set; }
        public string NUMCHEQUE { get; set; }
        public string BENEFICIARIO { get; set; }
        public string UUID { get; set; }
        public Nullable<System.DateTime> VERSION_SINC { get; set; }
        public string ID_OPERACION { get; set; }
        public string CVE_DOC_COMPPAGO { get; set; }
    }
}
