//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ulp_dl.aspel_sae80
{
    using System;
    using System.Collections.Generic;
    
    public partial class CVES_ALTER01
    {
        public string CVE_ART { get; set; }
        public string CVE_ALTER { get; set; }
        public string TIPO { get; set; }
        public string CVE_CLPV { get; set; }
    }
}
