//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ulp_dl.aspel_sae80
{
    using System;
    using System.Collections.Generic;
    
    public partial class DESEMBYAREA
    {
        public string PEDIDO { get; set; }
        public string DEPTO { get; set; }
        public string CUMPLIO { get; set; }
        public string OBSERVACIONES { get; set; }
    }
}
