//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ulp_dl.aspel_sae80
{
    using System;
    using System.Collections.Generic;
    
    public partial class ENLACE_LTPD01
    {
        public int E_LTPD { get; set; }
        public Nullable<int> REG_LTPD { get; set; }
        public Nullable<double> CANTIDAD { get; set; }
        public Nullable<double> PXRS { get; set; }
    }
}
