//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ulp_dl.aspel_sae80
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESTDPEDI
    {
        public string PEDIDO { get; set; }
        public int ADVO { get; set; }
        public int LIB { get; set; }
        public int SUR { get; set; }
        public int COR { get; set; }
        public int EST { get; set; }
        public int BOR { get; set; }
        public int INI { get; set; }
        public int COS { get; set; }
        public int EMP { get; set; }
        public int EMB { get; set; }
        public int ESP { get; set; }
        public System.DateTime FCH { get; set; }
    }
}
