//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ulp_dl.aspel_sae80
{
    using System;
    using System.Collections.Generic;
    
    public partial class FACTR01
    {
        public string TIP_DOC { get; set; }
        public string CVE_DOC { get; set; }
        public string CVE_CLPV { get; set; }
        public string STATUS { get; set; }
        public Nullable<int> DAT_MOSTR { get; set; }
        public string CVE_VEND { get; set; }
        public string CVE_PEDI { get; set; }
        public System.DateTime FECHA_DOC { get; set; }
        public Nullable<System.DateTime> FECHA_ENT { get; set; }
        public Nullable<System.DateTime> FECHA_VEN { get; set; }
        public Nullable<System.DateTime> FECHA_CANCELA { get; set; }
        public Nullable<double> CAN_TOT { get; set; }
        public Nullable<double> IMP_TOT1 { get; set; }
        public Nullable<double> IMP_TOT2 { get; set; }
        public Nullable<double> IMP_TOT3 { get; set; }
        public Nullable<double> IMP_TOT4 { get; set; }
        public Nullable<double> DES_TOT { get; set; }
        public Nullable<double> DES_FIN { get; set; }
        public Nullable<double> COM_TOT { get; set; }
        public string CONDICION { get; set; }
        public Nullable<int> CVE_OBS { get; set; }
        public Nullable<int> NUM_ALMA { get; set; }
        public string ACT_CXC { get; set; }
        public string ACT_COI { get; set; }
        public string ENLAZADO { get; set; }
        public string TIP_DOC_E { get; set; }
        public Nullable<int> NUM_MONED { get; set; }
        public Nullable<double> TIPCAMB { get; set; }
        public Nullable<int> NUM_PAGOS { get; set; }
        public Nullable<System.DateTime> FECHAELAB { get; set; }
        public Nullable<double> PRIMERPAGO { get; set; }
        public string RFC { get; set; }
        public Nullable<int> CTLPOL { get; set; }
        public string ESCFD { get; set; }
        public Nullable<int> AUTORIZA { get; set; }
        public string SERIE { get; set; }
        public Nullable<int> FOLIO { get; set; }
        public string AUTOANIO { get; set; }
        public Nullable<int> DAT_ENVIO { get; set; }
        public string CONTADO { get; set; }
        public Nullable<int> CVE_BITA { get; set; }
        public string BLOQ { get; set; }
        public string FORMAENVIO { get; set; }
        public Nullable<double> DES_FIN_PORC { get; set; }
        public Nullable<double> DES_TOT_PORC { get; set; }
        public Nullable<double> IMPORTE { get; set; }
        public Nullable<double> COM_TOT_PORC { get; set; }
        public string METODODEPAGO { get; set; }
        public string NUMCTAPAGO { get; set; }
        public string TIP_DOC_ANT { get; set; }
        public string DOC_ANT { get; set; }
        public string TIP_DOC_SIG { get; set; }
        public string DOC_SIG { get; set; }
        public string UUID { get; set; }
        public Nullable<System.DateTime> VERSION_SINC { get; set; }
        public string FORMADEPAGOSAT { get; set; }
        public string USO_CFDI { get; set; }
        public string TIP_TRASLADO { get; set; }
        public Nullable<int> NUM_ALM_DES { get; set; }
    }
}
