//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ulp_dl.aspel_sae80
{
    using System;
    using System.Collections.Generic;
    
    public partial class FOLCXC01
    {
        public string CVE_FOLIO { get; set; }
        public Nullable<double> IMPUESTO1 { get; set; }
        public Nullable<double> IMPUESTO2 { get; set; }
        public Nullable<double> IMPUESTO3 { get; set; }
        public Nullable<double> IMPUESTO4 { get; set; }
        public string REFERENCIA { get; set; }
        public string STATUS { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
        public Nullable<System.DateTime> FECHAELAB { get; set; }
        public Nullable<short> USUARIO { get; set; }
    }
}
