//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ulp_dl.aspel_sae80
{
    using System;
    using System.Collections.Generic;
    
    public partial class FOLIOSF01
    {
        public string TIP_DOC { get; set; }
        public int FOLIODESDE { get; set; }
        public Nullable<int> FOLIOHASTA { get; set; }
        public Nullable<int> AUTORIZA { get; set; }
        public string SERIE { get; set; }
        public string AUTOANIO { get; set; }
        public Nullable<int> ULT_DOC { get; set; }
        public string TIPO { get; set; }
        public Nullable<System.DateTime> FECH_ULT_DOC { get; set; }
        public string CBB { get; set; }
        public Nullable<System.DateTime> FECHAAPROBCBB { get; set; }
        public byte[] IMGCBB { get; set; }
        public string FOLIOPERSONALIZADO { get; set; }
        public string PARCIALIDAD { get; set; }
        public string STATUS { get; set; }
    }
}
