//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ulp_dl.aspel_sae80
{
    using System;
    using System.Collections.Generic;
    
    public partial class HNUMSER01
    {
        public string CVE_ART { get; set; }
        public string NUM_SER { get; set; }
        public Nullable<int> TIP_MOV { get; set; }
        public string TIP_DOC { get; set; }
        public string CVE_DOC { get; set; }
        public int ALMACEN { get; set; }
        public Nullable<int> REG_SERIE { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
        public string STATUS { get; set; }
        public Nullable<int> NO_PAR { get; set; }
    }
}
