//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ulp_dl.aspel_sae80
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMAGENES
    {
        public int ID { get; set; }
        public string NAME { get; set; }
        public string COD_CATALOGO { get; set; }
        public string COD_CLIENTE { get; set; }
        public string COLOR_1 { get; set; }
        public string COLOR_2 { get; set; }
        public string COLOR_3 { get; set; }
        public string COLOR_4 { get; set; }
        public string COLOR_5 { get; set; }
        public string COLOR_6 { get; set; }
        public string COMENTARIOS { get; set; }
        public Nullable<int> PUNTADAS { get; set; }
        public string COD_MFG { get; set; }
    }
}
