//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ulp_dl.aspel_sae80
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMPU01
    {
        public int CVE_ESQIMPU { get; set; }
        public string DESCRIPESQ { get; set; }
        public Nullable<double> IMPUESTO1 { get; set; }
        public Nullable<int> IMP1APLICA { get; set; }
        public Nullable<double> IMPUESTO2 { get; set; }
        public Nullable<int> IMP2APLICA { get; set; }
        public Nullable<double> IMPUESTO3 { get; set; }
        public Nullable<int> IMP3APLICA { get; set; }
        public Nullable<double> IMPUESTO4 { get; set; }
        public Nullable<int> IMP4APLICA { get; set; }
        public string STATUS { get; set; }
        public string UUID { get; set; }
        public Nullable<System.DateTime> VERSION_SINC { get; set; }
    }
}
