//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ulp_dl.aspel_sae80
{
    using System;
    using System.Collections.Generic;
    
    public partial class INFENVIO01
    {
        public int CVE_INFO { get; set; }
        public string CVE_CONS { get; set; }
        public string NOMBRE { get; set; }
        public string CALLE { get; set; }
        public string NUMINT { get; set; }
        public string NUMEXT { get; set; }
        public string CRUZAMIENTOS { get; set; }
        public string CRUZAMIENTOS2 { get; set; }
        public string POB { get; set; }
        public string CURP { get; set; }
        public string REFERDIR { get; set; }
        public string CVE_ZONA { get; set; }
        public Nullable<int> CVE_OBS { get; set; }
        public string STRNOGUIA { get; set; }
        public string STRMODOENV { get; set; }
        public Nullable<System.DateTime> FECHA_ENV { get; set; }
        public string NOMBRE_RECEP { get; set; }
        public string NO_RECEP { get; set; }
        public Nullable<System.DateTime> FECHA_RECEP { get; set; }
        public string COLONIA { get; set; }
        public string CODIGO { get; set; }
        public string ESTADO { get; set; }
        public string PAIS { get; set; }
        public string MUNICIPIO { get; set; }
        public string GUIA_ENV { get; set; }
        public string FAC_ENV { get; set; }
        public string ID_GUIA { get; set; }
        public string R_EVIDENCIA { get; set; }
        public string R_FACTURA { get; set; }
        public Nullable<System.DateTime> F_ENTREGA { get; set; }
        public string CVE_PED_TIEND { get; set; }
        public string PAQUETERIA { get; set; }
        public string CVE_PAIS_SAT { get; set; }
        public string REG_FISC { get; set; }
        public string FEEDDOCUMENT_GUIA { get; set; }
    }
}
