//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ulp_dl.aspel_sae80
{
    using System;
    using System.Collections.Generic;
    
    public partial class INTCOI01
    {
        public int CVE_INTCOI { get; set; }
        public Nullable<int> TRANSACCIO { get; set; }
        public string TIPOPOL { get; set; }
        public string NUMPOL { get; set; }
        public Nullable<System.DateTime> FECHAPOL { get; set; }
        public Nullable<System.DateTime> FECHAOPR { get; set; }
        public string SISTEMA { get; set; }
        public Nullable<short> NUMUSR { get; set; }
        public Nullable<int> OPERACION { get; set; }
        public Nullable<int> STATUS { get; set; }
        public string TIPPOLINT { get; set; }
        public string POLMODELO { get; set; }
        public Nullable<int> CTLPOL { get; set; }
        public string STATUSCLI { get; set; }
    }
}
