//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ulp_dl.aspel_sae80
{
    using System;
    using System.Collections.Generic;
    
    public partial class INTERFAZ_PLUS_CTRL_ENLACE_COMPRAS
    {
        public string TIP_DOC { get; set; }
        public string CVE_DOC { get; set; }
        public string STS { get; set; }
        public string CVE_DOC_SIG { get; set; }
        public string TIP_DOC_SIG { get; set; }
    }
}
