//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ulp_dl.aspel_sae80
{
    using System;
    using System.Collections.Generic;
    
    public partial class INVE_AMAZON01
    {
        public string CVE_ART { get; set; }
        public string ASIN { get; set; }
        public string SKU_AM { get; set; }
        public string EDO_PUBL_AM { get; set; }
        public string CONDICION { get; set; }
        public string MOD_ENVIO { get; set; }
        public string STATUS { get; set; }
        public string SUBMIT_ID { get; set; }
        public string TITULOPUB_AM { get; set; }
        public string TITULO_AM { get; set; }
        public string FABRICANTE_AM { get; set; }
        public string MARCA_AM { get; set; }
        public string TIPO_PROD_AM { get; set; }
        public string DESCR_AM { get; set; }
        public string ATRIBUTOS_AM { get; set; }
        public string CARAC_AM { get; set; }
        public string DISP_PUBL_AM { get; set; }
        public Nullable<System.DateTime> F_PUB_AM { get; set; }
        public string DISP_OFERTA { get; set; }
        public Nullable<System.DateTime> F_DES_OF { get; set; }
        public Nullable<System.DateTime> F_HAS_OF { get; set; }
        public string STATUS_INV { get; set; }
        public string SUBMIT_INV_ID { get; set; }
        public string STATUS_PRE { get; set; }
        public string SUBMIT_PRE_ID { get; set; }
        public string STATUS_ELIM { get; set; }
        public string SUBMIT_ELIM_ID { get; set; }
        public string FEEDDOCUMENT { get; set; }
        public string FEEDDOCUMENT_INV { get; set; }
        public string FEEDDOCUMENT_PRE { get; set; }
        public string FEEDDOCUMENT_ELIM { get; set; }
    }
}
