//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ulp_dl.aspel_sae80
{
    using System;
    using System.Collections.Generic;
    
    public partial class INVEN_CLARO01
    {
        public string CVE_ART { get; set; }
        public string CVE_PUBL_CS { get; set; }
        public string EDO_PUBL_CS { get; set; }
        public string EDO_PROD_CS { get; set; }
        public string DESC_CS { get; set; }
        public string SKU_CS { get; set; }
        public string EAN_CS { get; set; }
        public string CATEG_CS { get; set; }
        public string CVE_CATE_CS { get; set; }
        public string MARCA_CS { get; set; }
        public Nullable<int> TIEMP_EMBARQ { get; set; }
        public Nullable<double> LARGO_CS { get; set; }
        public Nullable<double> ALTO_CS { get; set; }
        public Nullable<double> ANCHO_CS { get; set; }
        public Nullable<System.DateTime> LAST_UPDATE_CS { get; set; }
        public string IMAGEN_CS { get; set; }
        public string DISP_PUBL_CS { get; set; }
        public Nullable<System.DateTime> F_CREA_CS { get; set; }
        public string FULFILLMENT { get; set; }
        public string DESCR_ESP { get; set; }
    }
}
