//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ulp_dl.aspel_sae80
{
    using System;
    using System.Collections.Generic;
    
    public partial class INVE01
    {
        public string CVE_ART { get; set; }
        public string DESCR { get; set; }
        public string LIN_PROD { get; set; }
        public string CON_SERIE { get; set; }
        public string UNI_MED { get; set; }
        public Nullable<double> UNI_EMP { get; set; }
        public string CTRL_ALM { get; set; }
        public Nullable<int> TIEM_SURT { get; set; }
        public Nullable<double> STOCK_MIN { get; set; }
        public Nullable<double> STOCK_MAX { get; set; }
        public string TIP_COSTEO { get; set; }
        public Nullable<int> NUM_MON { get; set; }
        public Nullable<System.DateTime> FCH_ULTCOM { get; set; }
        public Nullable<double> COMP_X_REC { get; set; }
        public Nullable<System.DateTime> FCH_ULTVTA { get; set; }
        public Nullable<double> PEND_SURT { get; set; }
        public Nullable<double> EXIST { get; set; }
        public Nullable<double> COSTO_PROM { get; set; }
        public Nullable<double> ULT_COSTO { get; set; }
        public Nullable<int> CVE_OBS { get; set; }
        public string TIPO_ELE { get; set; }
        public string UNI_ALT { get; set; }
        public Nullable<double> FAC_CONV { get; set; }
        public Nullable<double> APART { get; set; }
        public string CON_LOTE { get; set; }
        public string CON_PEDIMENTO { get; set; }
        public Nullable<double> PESO { get; set; }
        public Nullable<double> VOLUMEN { get; set; }
        public Nullable<int> CVE_ESQIMPU { get; set; }
        public Nullable<int> CVE_BITA { get; set; }
        public Nullable<double> VTAS_ANL_C { get; set; }
        public Nullable<double> VTAS_ANL_M { get; set; }
        public Nullable<double> COMP_ANL_C { get; set; }
        public Nullable<double> COMP_ANL_M { get; set; }
        public string PREFIJO { get; set; }
        public string TALLA { get; set; }
        public string COLOR { get; set; }
        public string CUENT_CONT { get; set; }
        public string CVE_IMAGEN { get; set; }
        public string BLK_CST_EXT { get; set; }
        public string STATUS { get; set; }
        public string MAN_IEPS { get; set; }
        public Nullable<int> APL_MAN_IMP { get; set; }
        public Nullable<double> CUOTA_IEPS { get; set; }
        public string APL_MAN_IEPS { get; set; }
        public string UUID { get; set; }
        public Nullable<System.DateTime> VERSION_SINC { get; set; }
        public Nullable<System.DateTime> VERSION_SINC_FECHA_IMG { get; set; }
        public string CVE_PRODSERV { get; set; }
        public string CVE_UNIDAD { get; set; }
        public string MAT_PELI { get; set; }
        public string TITULO_ML { get; set; }
        public string ID_CATALOGO { get; set; }
        public string EN_CATALOGO { get; set; }
        public string IMAGEN_ML { get; set; }
        public Nullable<System.DateTime> F_CREA_ML { get; set; }
        public string LAST_UPDATE_ML { get; set; }
        public string CVE_CATE_ML { get; set; }
        public string DISPONIBLE_PUBL { get; set; }
        public string CAMPOS_CATEG_ML { get; set; }
        public string CVE_PUBL_ML { get; set; }
        public string ENVIO_ML { get; set; }
        public Nullable<double> ANCHO_ML { get; set; }
        public Nullable<double> ALTO_ML { get; set; }
        public Nullable<double> LARGO_ML { get; set; }
        public string MODO_ENVIO_ML { get; set; }
        public string TIPO_PUBL_ML { get; set; }
        public string CONDICION_ML { get; set; }
        public string CATEG_ML { get; set; }
        public string EDO_PUBL_ML { get; set; }
    }
}
