//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ulp_dl.aspel_sae80
{
    using System;
    using System.Collections.Generic;
    
    public partial class INVE_CLIB01
    {
        public string CVE_PROD { get; set; }
        public string CAMPLIB1 { get; set; }
        public string CAMPLIB2 { get; set; }
        public string CAMPLIB3 { get; set; }
        public Nullable<int> CAMPLIB4 { get; set; }
        public Nullable<double> CAMPLIB5 { get; set; }
        public Nullable<double> CAMPLIB6 { get; set; }
        public string CAMPLIB7 { get; set; }
    }
}
