//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ulp_dl.aspel_sae80
{
    using System;
    using System.Collections.Generic;
    
    public partial class INVFIS01
    {
        public string CVE_ART { get; set; }
        public int CVE_ALM { get; set; }
        public Nullable<double> EXISTCONG { get; set; }
        public Nullable<int> SECAPTURO { get; set; }
        public Nullable<double> EXISTREAL { get; set; }
    }
}
