//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ulp_dl.aspel_sae80
{
    using System;
    using System.Collections.Generic;
    
    public partial class ISIP_MONITOR_FACT_ANT
    {
        public int ID { get; set; }
        public string FOL_MOV_MINVE { get; set; }
        public string REFER { get; set; }
        public string STS { get; set; }
        public string CVE_ART { get; set; }
        public int ALMACEN { get; set; }
        public double CANT { get; set; }
        public System.DateTime FCH_TRANSFER { get; set; }
        public Nullable<System.DateTime> FCH_BACK { get; set; }
    }
}
