//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ulp_dl.aspel_sae80
{
    using System;
    using System.Collections.Generic;
    
    public partial class ISIP_TRANSFERENCIAS_VIRTUALES
    {
        public int ID { get; set; }
        public string PEDIDO { get; set; }
        public string CVE_ART { get; set; }
        public Nullable<int> CVE_ALM_DEST { get; set; }
        public Nullable<int> CANTIDAD { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
        public string CVE_FOLIO { get; set; }
        public Nullable<int> NUM_MOV { get; set; }
    }
}
