//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ulp_dl.aspel_sae80
{
    using System;
    using System.Collections.Generic;
    
    public partial class ISIP_FACT_ANT_CTRL
    {
        public int ID { get; set; }
        public string FOL_MOV_MINVE { get; set; }
        public string REFER { get; set; }
        public string STS { get; set; }
        public string CVE_ART { get; set; }
        public short ALMA_ORI { get; set; }
        public short ALMA_DEST { get; set; }
        public int CANT { get; set; }
        public Nullable<System.DateTime> FCH_BACK { get; set; }
        public Nullable<System.DateTime> FCH_TRANSFER { get; set; }
    }
}
