//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ulp_dl.aspel_sae80
{
    using System;
    using System.Collections.Generic;
    
    public partial class ISIP_NAMESPACES
    {
        public string NAMESPACE { get; set; }
        public string STS { get; set; }
        public string IS_PR_NE { get; set; }
        public string NAME { get; set; }
        public string DETAILS { get; set; }
        public string PARENT { get; set; }
        public Nullable<System.DateTime> FCH_ALT { get; set; }
        public Nullable<System.DateTime> FCH_MOD { get; set; }
    }
}
