//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ulp_dl.aspel_sae80
{
    using System;
    using System.Collections.Generic;
    
    public partial class KITS01
    {
        public string CVE_ART { get; set; }
        public string CVE_PROD { get; set; }
        public Nullable<double> PORCEN { get; set; }
        public Nullable<double> CANTIDAD { get; set; }
    }
}
