//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ulp_dl.aspel_sae80
{
    using System;
    using System.Collections.Generic;
    
    public partial class LNKOLKC01
    {
        public int NCONTACTO { get; set; }
        public Nullable<short> USUARIOSAE { get; set; }
        public string ID_OUTLOOK { get; set; }
        public string NOMBRE_USUARIOSAE { get; set; }
    }
}
