//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ulp_dl.aspel_sae80
{
    using System;
    using System.Collections.Generic;
    
    public partial class LTPD01
    {
        public string CVE_ART { get; set; }
        public string LOTE { get; set; }
        public string PEDIMENTO { get; set; }
        public Nullable<int> CVE_ALM { get; set; }
        public Nullable<System.DateTime> FCHCADUC { get; set; }
        public Nullable<System.DateTime> FCHADUANA { get; set; }
        public Nullable<System.DateTime> FCHULTMOV { get; set; }
        public string NOM_ADUAN { get; set; }
        public Nullable<double> CANTIDAD { get; set; }
        public int REG_LTPD { get; set; }
        public Nullable<int> CVE_OBS { get; set; }
        public string CIUDAD { get; set; }
        public string FRONTERA { get; set; }
        public Nullable<System.DateTime> FEC_PROD_LT { get; set; }
        public string GLN { get; set; }
        public string STATUS { get; set; }
        public string PEDIMENTOSAT { get; set; }
    }
}
