//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ulp_dl.aspel_sae80
{
    using System;
    using System.Collections.Generic;
    
    public partial class MINVE01
    {
        public string CVE_ART { get; set; }
        public int ALMACEN { get; set; }
        public int NUM_MOV { get; set; }
        public int CVE_CPTO { get; set; }
        public Nullable<System.DateTime> FECHA_DOCU { get; set; }
        public string TIPO_DOC { get; set; }
        public string REFER { get; set; }
        public string CLAVE_CLPV { get; set; }
        public string VEND { get; set; }
        public Nullable<double> CANT { get; set; }
        public Nullable<double> CANT_COST { get; set; }
        public Nullable<double> PRECIO { get; set; }
        public Nullable<double> COSTO { get; set; }
        public string AFEC_COI { get; set; }
        public Nullable<int> CVE_OBS { get; set; }
        public Nullable<int> REG_SERIE { get; set; }
        public string UNI_VENTA { get; set; }
        public Nullable<int> E_LTPD { get; set; }
        public Nullable<double> EXIST_G { get; set; }
        public Nullable<double> EXISTENCIA { get; set; }
        public string TIPO_PROD { get; set; }
        public Nullable<double> FACTOR_CON { get; set; }
        public Nullable<System.DateTime> FECHAELAB { get; set; }
        public Nullable<int> CTLPOL { get; set; }
        public string CVE_FOLIO { get; set; }
        public Nullable<int> SIGNO { get; set; }
        public string COSTEADO { get; set; }
        public Nullable<double> COSTO_PROM_INI { get; set; }
        public Nullable<double> COSTO_PROM_FIN { get; set; }
        public Nullable<double> COSTO_PROM_GRAL { get; set; }
        public string DESDE_INVE { get; set; }
        public Nullable<int> MOV_ENLAZADO { get; set; }
    }
}
