//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ulp_dl.aspel_sae80
{
    using System;
    using System.Collections.Generic;
    
    public partial class MONED01
    {
        public int NUM_MONED { get; set; }
        public string DESCR { get; set; }
        public string SIMBOLO { get; set; }
        public Nullable<double> TCAMBIO { get; set; }
        public Nullable<System.DateTime> FULTCAMB { get; set; }
        public string STATUS { get; set; }
        public string UUID { get; set; }
        public Nullable<System.DateTime> VERSION_SINC { get; set; }
        public string CVE_MONED { get; set; }
    }
}
