//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ulp_dl.aspel_sae80
{
    using System;
    using System.Collections.Generic;
    
    public partial class NUMSER01
    {
        public string CVE_ART { get; set; }
        public string NUM_SER { get; set; }
        public string STATUS { get; set; }
        public int ALMACEN { get; set; }
        public Nullable<double> COSTO { get; set; }
        public string DOCTO_ENT { get; set; }
        public Nullable<System.DateTime> FECHA_ENT { get; set; }
    }
}
