//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ulp_dl.aspel_sae80
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPERADOR01
    {
        public string CVE_OPE { get; set; }
        public string NOM_OPE { get; set; }
        public string XML_OPE { get; set; }
        public string TIPO_FIG { get; set; }
    }
}
