//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ulp_dl.aspel_sae80
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAGOLINEA01
    {
        public string ID_OPERACION { get; set; }
        public int ID_CLIENTRAN { get; set; }
        public Nullable<int> AUTORIZA { get; set; }
        public string TARJETA { get; set; }
        public string TIP_DOC { get; set; }
        public Nullable<System.DateTime> FECHA_OPER { get; set; }
        public string ESTATUS { get; set; }
        public string TIP_OPER { get; set; }
        public string APLICADO { get; set; }
        public string REFER { get; set; }
        public Nullable<double> MONTO { get; set; }
        public Nullable<int> NUM_CPTO { get; set; }
        public string PROVEEDOR { get; set; }
        public string XML_PL { get; set; }
    }
}
