//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ulp_dl.aspel_sae80
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAGOS_PED_TIENDA01
    {
        public string CVE_DOC { get; set; }
        public string CVE_PAGO { get; set; }
        public int NUM_PAR { get; set; }
        public string EDO_PAGO { get; set; }
        public string DET_EDO { get; set; }
        public Nullable<System.DateTime> F_CREACION { get; set; }
        public Nullable<System.DateTime> F_APROB { get; set; }
        public string TIPO_PAGO { get; set; }
        public string MONEDA { get; set; }
        public Nullable<double> IMPORTE { get; set; }
    }
}
