//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ulp_dl.aspel_sae80
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAGOCODI01
    {
        public string IDMENSAJE { get; set; }
        public string NUMCLI { get; set; }
        public string CVE_CLIE { get; set; }
        public string REFER { get; set; }
        public Nullable<int> ID_MOV { get; set; }
        public Nullable<int> NUM_CPTO { get; set; }
        public Nullable<int> NUM_CARGO { get; set; }
        public Nullable<int> ESTADO { get; set; }
        public string METODO { get; set; }
        public Nullable<double> MONTO { get; set; }
        public string FOLIO { get; set; }
        public string USADO { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
        public Nullable<System.DateTime> FECHA_MODIFICACION { get; set; }
    }
}
