//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ulp_dl.aspel_sae80
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAR_PED_CLARO01
    {
        public string CVE_DOC { get; set; }
        public int NUM_PAR { get; set; }
        public string CVE_ART { get; set; }
        public string CLARO_ID { get; set; }
        public string TITULO_ART { get; set; }
        public string ASIGNADO { get; set; }
        public string ID_PED_REL { get; set; }
        public Nullable<double> IMPORTE { get; set; }
        public Nullable<double> CST_ENVIO { get; set; }
        public Nullable<System.DateTime> F_ASIGNA { get; set; }
        public Nullable<System.DateTime> F_ENVIO { get; set; }
    }
}
