//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ulp_dl.aspel_sae80
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAR_PED_TIEND01
    {
        public string CVE_DOC { get; set; }
        public int NUM_PAR { get; set; }
        public string CVE_ART { get; set; }
        public string CVE_SAE { get; set; }
        public string TITULO { get; set; }
        public string CATEGORIA { get; set; }
        public string CONDICION { get; set; }
        public Nullable<double> CANT { get; set; }
        public Nullable<double> PREC { get; set; }
        public string CVE_MONED { get; set; }
        public Nullable<double> TOT_PARTIDA { get; set; }
    }
}
