//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ulp_dl.aspel_sae80
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAR_COMPD01
    {
        public string CVE_DOC { get; set; }
        public int NUM_PAR { get; set; }
        public string CVE_ART { get; set; }
        public Nullable<double> CANT { get; set; }
        public Nullable<double> PXR { get; set; }
        public Nullable<double> PREC { get; set; }
        public Nullable<double> COST { get; set; }
        public Nullable<double> IMPU1 { get; set; }
        public Nullable<double> IMPU2 { get; set; }
        public Nullable<double> IMPU3 { get; set; }
        public Nullable<double> IMPU4 { get; set; }
        public Nullable<short> IMP1APLA { get; set; }
        public Nullable<short> IMP2APLA { get; set; }
        public Nullable<short> IMP3APLA { get; set; }
        public Nullable<short> IMP4APLA { get; set; }
        public Nullable<double> TOTIMP1 { get; set; }
        public Nullable<double> TOTIMP2 { get; set; }
        public Nullable<double> TOTIMP3 { get; set; }
        public Nullable<double> TOTIMP4 { get; set; }
        public Nullable<double> DESCU { get; set; }
        public string ACT_INV { get; set; }
        public Nullable<double> TIP_CAM { get; set; }
        public string UNI_VENTA { get; set; }
        public string TIPO_ELEM { get; set; }
        public string TIPO_PROD { get; set; }
        public Nullable<int> CVE_OBS { get; set; }
        public Nullable<int> REG_SERIE { get; set; }
        public Nullable<int> E_LTPD { get; set; }
        public Nullable<double> FACTCONV { get; set; }
        public Nullable<double> COST_DEV { get; set; }
        public Nullable<int> NUM_ALM { get; set; }
        public Nullable<double> MINDIRECTO { get; set; }
        public Nullable<int> NUM_MOV { get; set; }
        public Nullable<double> TOT_PARTIDA { get; set; }
        public string MAN_IEPS { get; set; }
        public Nullable<int> APL_MAN_IMP { get; set; }
        public Nullable<double> CUOTA_IEPS { get; set; }
        public string APL_MAN_IEPS { get; set; }
        public Nullable<double> MTO_PORC { get; set; }
        public Nullable<double> MTO_CUOTA { get; set; }
        public Nullable<int> CVE_ESQ { get; set; }
        public string DESCR_ART { get; set; }
    }
}
