//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ulp_dl.aspel_sae80
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAR_PED_AMAZON01
    {
        public string CVE_DOC { get; set; }
        public int NUM_PAR { get; set; }
        public string CVE_PAR { get; set; }
        public string ASIN { get; set; }
        public string SKU_AM { get; set; }
        public string TITULO { get; set; }
        public Nullable<int> CANT { get; set; }
        public Nullable<int> CANT_ENVIADA { get; set; }
        public Nullable<double> PREC { get; set; }
        public string CVE_MONED { get; set; }
        public string CVE_MONED_ENV { get; set; }
        public Nullable<double> COST_ENVIO { get; set; }
        public string ES_REGALO { get; set; }
        public string MSG_REGALO { get; set; }
        public string CVE_MONED_REGA { get; set; }
        public Nullable<double> COST_REGALO { get; set; }
        public string TIPO_ENVOLTURA { get; set; }
        public string CVE_MONED_DESCU { get; set; }
        public Nullable<double> DESCUENTO { get; set; }
        public Nullable<double> TOT_PARTIDA { get; set; }
    }
}
