//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ulp_dl.aspel_sae80
{
    using System;
    using System.Collections.Generic;
    
    public partial class PARAM_DOMFISCAL01
    {
        public int NUM_EMP { get; set; }
        public string CALLE { get; set; }
        public string NUMERO_EXT { get; set; }
        public string NUMERO_INT { get; set; }
        public string COLONIA { get; set; }
        public string LOCALIDAD { get; set; }
        public string REFERENCIA { get; set; }
        public string MUNICIPIO { get; set; }
        public string ESTADO { get; set; }
        public string PAIS { get; set; }
        public string CP { get; set; }
        public string CRUZAMIENTO1 { get; set; }
        public string CRUZAMIENTO2 { get; set; }
        public string LUGARDEEXPED { get; set; }
    }
}
