//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ulp_dl.aspel_sae80
{
    using System;
    using System.Collections.Generic;
    
    public partial class PARAM_INVENTARIO01
    {
        public int NUM_EMP { get; set; }
        public string INTEGRAFACTURAS { get; set; }
        public string INTEGRACOMPRAS { get; set; }
        public string CAMBIOEXISTENCIAS { get; set; }
        public string DIGITOVERIFICA { get; set; }
        public string MULTIALMACEN { get; set; }
        public Nullable<int> CVEPRECMINIMO { get; set; }
        public Nullable<int> MOVTRASPASOENTRADA { get; set; }
        public Nullable<int> MOVTRASPASOSALIDA { get; set; }
        public Nullable<int> NUMDECIMALES { get; set; }
        public string GPOPRODLEYENDASECC1 { get; set; }
        public string GPOPRODLEYENDASECC2 { get; set; }
        public string FTOMOVSINVENTARIO { get; set; }
        public string VERENALTANUMSERIE { get; set; }
        public string VERENALTALOTEYPED { get; set; }
        public string NOMBREIMP1 { get; set; }
        public string NOMBREIMP2 { get; set; }
        public string NOMBREIMP3 { get; set; }
        public string NOMBREIMP4 { get; set; }
        public Nullable<double> PORCENTAJEIMP1 { get; set; }
        public Nullable<double> PORCENTAJEIMP2 { get; set; }
        public Nullable<double> PORCENTAJEIMP3 { get; set; }
        public Nullable<double> PORCENTAJEIMP4 { get; set; }
        public Nullable<int> ALMACENPREDETER { get; set; }
        public string INVINTEGRADO { get; set; }
        public string MODALMACEN { get; set; }
        public Nullable<System.DateTime> FCHCIERREDOCTOS { get; set; }
        public string SERVICIOFLETE { get; set; }
        public string COSTEARXALMACEN { get; set; }
        public string PRODFACTGLOB { get; set; }
        public string NOMBREIMP1SAT { get; set; }
        public string NOMBREIMP2SAT { get; set; }
        public string NOMBREIMP3SAT { get; set; }
        public string NOMBREIMP4SAT { get; set; }
        public Nullable<double> PORCENTAJERESICO { get; set; }
    }
}
