//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ulp_dl.aspel_sae80
{
    using System;
    using System.Collections.Generic;
    
    public partial class PARAM_TIENDAS01
    {
        public int ID_USUARIO { get; set; }
        public int NUM_EMP { get; set; }
        public string CVE_TIENDA { get; set; }
        public string ID_USER_TIEND { get; set; }
        public string INICIAR_AUTO { get; set; }
        public Nullable<System.DateTime> EXPIRACION_TOKEN { get; set; }
        public string REFRESH_TOKEN { get; set; }
        public string ACCES_TOKEN { get; set; }
        public string CVE_PV_CS { get; set; }
        public string PARAM_DEFAULT { get; set; }
        public Nullable<int> CVE_ALM { get; set; }
        public Nullable<int> LISTA_PREC { get; set; }
        public Nullable<int> LISTA_PREC_OFER { get; set; }
        public string SERIE { get; set; }
        public string MODO_EXIST { get; set; }
        public string CVE_CLIE { get; set; }
    }
}
