//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ulp_dl.aspel_sae80
{
    using System;
    using System.Collections.Generic;
    
    public partial class PARAM_DATOSBANCARIOS01
    {
        public int NUM_EMP { get; set; }
        public string BANCO { get; set; }
        public string RFC { get; set; }
        public string CUENTA { get; set; }
    }
}
