//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ulp_dl.aspel_sae80
{
    using System;
    using System.Collections.Generic;
    
    public partial class PARAM_DATOSGRALES01
    {
        public int NUM_EMP { get; set; }
        public string REDON_MONTOS { get; set; }
        public string REDON_COSTOS { get; set; }
        public string CHARCOMPDOS { get; set; }
        public string POL_DESC { get; set; }
        public string CXCCLIEMOSTR { get; set; }
        public string MULTIMONEDA { get; set; }
        public string VALENLINEA { get; set; }
        public string SOLICITATIPOCAMBIO { get; set; }
        public string MOSTRARIMAGCONSULTA { get; set; }
        public Nullable<int> ESQIMPUESTO { get; set; }
        public Nullable<double> DESCCOMERCIAL { get; set; }
        public string CAJONINSTALADO { get; set; }
        public string PUERTOCAJON { get; set; }
        public string SECAPERTURA { get; set; }
        public string SECINICIO { get; set; }
        public string SECCONFIRMA { get; set; }
        public Nullable<int> MONEDAPRED { get; set; }
        public Nullable<double> IMPGLOBAL { get; set; }
        public Nullable<double> TIPOCAMBIO { get; set; }
        public Nullable<int> NUMEMPCOI { get; set; }
        public string CONINTOUTLOOK { get; set; }
        public Nullable<int> NUMDEC_ENMONTOS { get; set; }
        public string PAGOPORINTERNET { get; set; }
        public string REGSXDEMANDA { get; set; }
        public Nullable<int> TAMPAQUETE { get; set; }
        public string BITACORA_CLIENTES { get; set; }
        public string BITACORA_FACTURAS { get; set; }
        public string BITACORA_INVENTARIO { get; set; }
        public string BITACORA_PROVEEDOR { get; set; }
        public string BITACORA_COMPRAS { get; set; }
        public string NOSERVPAGOXINTER { get; set; }
        public string BITACORA_UTILERIAS { get; set; }
        public string BITACORA_ESTADISTICAS { get; set; }
        public string BITACORA_CONFIGSISTEMA { get; set; }
        public string RUTAREPORTES { get; set; }
        public Nullable<int> NUMDEC_ENCOSTOYPRECIO { get; set; }
        public Nullable<int> NUMDEC_PORCENTAJES { get; set; }
        public string CORREOSERVIDOR { get; set; }
        public Nullable<int> CORREOPUERTO { get; set; }
        public string CORREOUSUARIO { get; set; }
        public string CORREOCONTRASENIA { get; set; }
        public string CORREOCONSEG { get; set; }
        public string CORREOAUTEN { get; set; }
        public Nullable<int> CORREOPROVEEDOR { get; set; }
        public string DESGLOSEIMP1 { get; set; }
        public string DESGLOSEIMP2 { get; set; }
        public string DESGLOSEIMP3 { get; set; }
        public string DESGLOSEIMP4 { get; set; }
        public string REFBANCO { get; set; }
        public string NUMCTAPAGO { get; set; }
        public Nullable<int> VERSIONREESTRUCTURADA { get; set; }
        public Nullable<double> LAT_GENERAL { get; set; }
        public Nullable<double> LON_GENERAL { get; set; }
        public Nullable<double> LAT_ENVIO { get; set; }
        public Nullable<double> LON_ENVIO { get; set; }
        public string TIEMPOAIRE { get; set; }
        public string BITACORA_TIENDAS { get; set; }
    }
}
