//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ulp_dl.aspel_sae80
{
    using System;
    using System.Collections.Generic;
    
    public partial class PARAM_CODI01
    {
        public int NUM_EMP { get; set; }
        public string ALIAS_CERT { get; set; }
        public string CONFIG_CODI { get; set; }
        public string DIG_VERIF { get; set; }
        public string CERT_CODI { get; set; }
        public string CUENTA_BENEF { get; set; }
        public string CVE_BANCO { get; set; }
        public string KEYSOURCE { get; set; }
        public string CVE_ACCESO_CERT { get; set; }
        public string PRIVATE_KEY { get; set; }
        public byte[] SELLOCERT_ARCH { get; set; }
        public byte[] SELLOPRIVKEY_ARCH { get; set; }
        public string CONTRASENIA { get; set; }
        public string KEYORIGINAL { get; set; }
        public string CODI_NOMBREVEND { get; set; }
    }
}
