//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ulp_dl.aspel_sae80
{
    using System;
    using System.Collections.Generic;
    
    public partial class PARAM_CLIENTES01
    {
        public int NUM_EMP { get; set; }
        public int DIASCREDITO { get; set; }
        public string CLAVESECUENCIAL { get; set; }
        public string CXCOPINTEGRADO { get; set; }
        public Nullable<int> TIPOAGRUPADOCTOS { get; set; }
        public Nullable<int> GANANCIACAMBIARIA { get; set; }
        public Nullable<int> PERDIDACAMBIARIA { get; set; }
        public string MANEJOFOLIO { get; set; }
        public string FOLIO { get; set; }
        public Nullable<System.DateTime> FECHALIMDEMOV { get; set; }
        public string VERCITASINICIO { get; set; }
        public Nullable<int> AJUSTECARGO { get; set; }
        public Nullable<int> AJUSTEABONO { get; set; }
    }
}
