//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ulp_dl.aspel_sae80
{
    using System;
    using System.Collections.Generic;
    
    public partial class PARAM_FOLIOSF01
    {
        public int NUM_EMP { get; set; }
        public string NUMFOLIO { get; set; }
        public string CVEFOLIO { get; set; }
        public string TIPODOCTO { get; set; }
        public string TIPO { get; set; }
        public string SERIE { get; set; }
        public string SEPARADOR { get; set; }
        public string FTOEMISION { get; set; }
        public string MASCARA { get; set; }
        public Nullable<int> FOLIOINICIAL { get; set; }
        public Nullable<int> FOLIOFINAL { get; set; }
        public string ARCHCONFIG { get; set; }
        public Nullable<int> LONGITUD { get; set; }
        public string CALLE { get; set; }
        public string NUMEROEXT { get; set; }
        public string NUMEROINT { get; set; }
        public string COLONIA { get; set; }
        public string LOCALIDAD { get; set; }
        public string REFERENCIA { get; set; }
        public string MUNICIPIO { get; set; }
        public string ESTADO { get; set; }
        public string PAIS { get; set; }
        public string CP { get; set; }
        public string CRUZAMIENTO1 { get; set; }
        public string CRUZAMIENTO2 { get; set; }
        public string SELLOCERTIF { get; set; }
        public string SELLOPRIVKEY { get; set; }
        public string CVEACCESOCERT { get; set; }
        public Nullable<int> AVISASELLO { get; set; }
        public string USUARIOPAC { get; set; }
        public string PASSWORDPAC { get; set; }
        public string PROVEEDORPAC { get; set; }
        public string FIRMACONTRATO { get; set; }
        public string IDSESIONPAC { get; set; }
        public string REGIMENFISCAL { get; set; }
        public string LUGARDEEXPEDICION { get; set; }
        public string PARCIALIDAD { get; set; }
        public string PLANTILLA { get; set; }
        public string FOLIOPERSONALIZADO { get; set; }
        public string STATUS { get; set; }
        public byte[] SELLOCERTIF_ARCH { get; set; }
        public byte[] SELLOPRIVKEY_ARCH { get; set; }
        public string REGIMENFISCALSAT { get; set; }
        public string FTOEMISIONCFDI33 { get; set; }
        public string UBI_EMI { get; set; }
        public string CAP_COM_EXT { get; set; }
        public string FTOEMISIONCFDI40 { get; set; }
        public Nullable<int> ZONAHORARIABASE { get; set; }
        public Nullable<int> ZONAHORARIACP { get; set; }
    }
}
