//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ulp_dl.aspel_sae80
{
    using System;
    using System.Collections.Generic;
    
    public partial class PARAM_TIPODOCTOSF01
    {
        public int NUM_EMP { get; set; }
        public string MODULO { get; set; }
        public string TIPODOCTO { get; set; }
        public string FOLIOSECUENCIAL { get; set; }
        public string ARCHCONFIGNOSEC { get; set; }
        public string FTOEMISIONNOSEC { get; set; }
        public string ARCHPLANTILLACORREO { get; set; }
        public string MANEJARVIGENCIACOTIZ { get; set; }
        public Nullable<int> DIASVIGENCIACOTIZ { get; set; }
        public Nullable<int> IDXFTOFOLIOCONFIG { get; set; }
        public string SERIEDEFAULT { get; set; }
    }
}
