//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ulp_dl.aspel_sae80
{
    using System;
    using System.Collections.Generic;
    
    public partial class PARAM_COMPRAS01
    {
        public int NUM_EMP { get; set; }
        public string ACUMCOMPVTASENLINEA { get; set; }
        public string ALTACLIEPROVENCAPTURA { get; set; }
        public string ALTAPRODENCAPTURA { get; set; }
        public Nullable<int> NUMCPTOCOMPVTASPLAZOS { get; set; }
        public Nullable<int> NUMCPTOINTXCOMPVTAPLAZO { get; set; }
        public Nullable<int> NUMCPTORETCLIEPROV { get; set; }
        public Nullable<int> NUMIMPUESTO { get; set; }
        public string MANEJOFLETE { get; set; }
        public Nullable<double> MONTOFLETE { get; set; }
        public Nullable<double> IMPFLETE { get; set; }
        public Nullable<System.DateTime> FCHCIERREDOCTOS { get; set; }
        public Nullable<int> ACUMULARINDCXP { get; set; }
        public string MODULO { get; set; }
        public string MODIFICARALMACEN { get; set; }
        public string REGISTROPAGOSCOMP { get; set; }
        public string POLIZASENLINEACOMP { get; set; }
        public string POLIZASENLINEACOMPDEVOL { get; set; }
        public Nullable<int> POLIZAAGRUPCOMP { get; set; }
        public Nullable<int> POLIZAAGRUPCOMPDEVOL { get; set; }
    }
}
