//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ulp_dl.aspel_sae80
{
    using System;
    using System.Collections.Generic;
    
    public partial class PARAM_PARTIDASFACT01
    {
        public int NUM_EMP { get; set; }
        public string CAPENALTADOCTODESCTO { get; set; }
        public string CAPENALTADOCTOIMP { get; set; }
        public string CAPENALTADOCTOCOMISION { get; set; }
        public string CAPALMACENXPARTIDAS { get; set; }
        public string CAPENALTADOCTOOBS { get; set; }
        public string VERENCSTATIPOPROD { get; set; }
        public string VERENCSTANUMSERIE { get; set; }
        public string VERENCSTALOTEPED { get; set; }
        public string VERENCSTAOBS { get; set; }
        public string VERENCSTAAPARTADOS { get; set; }
        public string VERENCSTADSGLSGPOPROD { get; set; }
        public string VERENCAPTIPOPROD { get; set; }
        public string VERENCAPNUMSERIE { get; set; }
        public string VERENCAPLOTEPED { get; set; }
        public string VERENCAPOBS { get; set; }
        public string VERENCAPAPARTADOS { get; set; }
        public string VERENCAPDESCRPROD { get; set; }
        public string VERENCAPCOSTOPROD { get; set; }
        public string VERENCAPCLVESAT { get; set; }
    }
}
