//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ulp_dl.aspel_sae80
{
    using System;
    using System.Collections.Generic;
    
    public partial class PARAM_FOLIOSC01
    {
        public int NUM_EMP { get; set; }
        public string NUMFOLIO { get; set; }
        public string CVEFOLIO { get; set; }
        public string TIPODOCTO { get; set; }
        public string TIPO { get; set; }
        public string SERIE { get; set; }
        public Nullable<int> FOLIOINICIAL { get; set; }
        public string SEPARADOR { get; set; }
        public string FTOEMISION { get; set; }
        public string ARCHCONFIG { get; set; }
        public string MASCARA { get; set; }
        public Nullable<int> LONGITUD { get; set; }
    }
}
