//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ulp_dl.aspel_sae80
{
    using System;
    using System.Collections.Generic;
    
    public partial class PARAM_FACTURAELECTRONICA01
    {
        public int NUM_EMP { get; set; }
        public string SELLOCERTIF { get; set; }
        public string SELLOPRIVKEY { get; set; }
        public string CVEACCESOCERT { get; set; }
        public Nullable<int> AVISASELLO { get; set; }
        public string RFCMOSTR { get; set; }
        public string RUTAADDENDAF { get; set; }
        public string RUTAADDENDAD { get; set; }
        public string RUTANAMESPACE { get; set; }
        public string DESGDESC { get; set; }
        public Nullable<int> VERSIONCOMPROBANTEDIGITAL { get; set; }
        public string TIPOPACGENERAL { get; set; }
        public string USUARIOPAC { get; set; }
        public string PASSWORDPAC { get; set; }
        public string PROVEEDORPAC { get; set; }
        public string FIRMACONTRATO { get; set; }
        public string IDSESIONPACGRAL { get; set; }
        public string USUARIOPAC_CANCEL { get; set; }
        public string PASSWORDPAC_CANCEL { get; set; }
        public string PROVEEDORPAC_CANCEL { get; set; }
        public string NOTIFICACANCELACIONENAUTO { get; set; }
        public string REGIMENFISCAL { get; set; }
        public Nullable<int> DESPLIEGUEKITXML { get; set; }
        public byte[] SELLOCERTIF_ARCH { get; set; }
        public byte[] SELLOPRIVKEY_ARCH { get; set; }
        public string REGIMENFISCALSAT { get; set; }
        public Nullable<double> MTOMAXFACT { get; set; }
        public string CANCELAENFORMAMANUAL { get; set; }
        public string RUTAADDENDAG { get; set; }
        public string RUTAADDENDAE { get; set; }
        public string RUTAADDENDAT { get; set; }
    }
}
