//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ulp_dl.aspel_sae80
{
    using System;
    using System.Collections.Generic;
    
    public partial class PARAM_DATOSBD01
    {
        public int NUM_EMP { get; set; }
        public string RUTADATOS { get; set; }
        public string DRIVER { get; set; }
        public string USUARIO { get; set; }
        public string RUTATRABAJO { get; set; }
        public string VERSIONBD { get; set; }
    }
}
