//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ulp_dl.aspel_sae80
{
    using System;
    using System.Collections.Generic;
    
    public partial class PARAM_DATOSEMP01
    {
        public int NUM_EMP { get; set; }
        public string NOMBRE_EMPRESA { get; set; }
        public string DIRECCION { get; set; }
        public string POBLACION { get; set; }
        public string RFC { get; set; }
        public string REG_ESTATAL { get; set; }
        public byte[] LOGO_EMPRESA { get; set; }
        public string ASIGNAVALPREDCVEPRODSAT { get; set; }
        public string VALPREDCVEPRODUCTOSAT { get; set; }
        public string ASIGNAVALPREDUNIMEDSAT { get; set; }
        public string VALPREDUNIMEDPRODSAT { get; set; }
        public string CLIE_FACTGLOBAL { get; set; }
    }
}
