//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ulp_dl.aspel_sae80
{
    using System;
    using System.Collections.Generic;
    
    public partial class PARAM_CTACONTABLE01
    {
        public int NUM_EMP { get; set; }
        public string VENTAS { get; set; }
        public string DESCFINANVTAS { get; set; }
        public string IMPXPAGAR { get; set; }
        public string DEVOLVENTAS { get; set; }
        public string VENTASERVICIOS { get; set; }
        public string CLIENTES { get; set; }
        public string ALMACEN { get; set; }
        public string DESCFINANCOMP { get; set; }
        public string IMPXACREDITAR { get; set; }
        public string DEVOLCOMPRAS { get; set; }
        public string COMPRASERVICIOS { get; set; }
        public string PROVEEDORES { get; set; }
        public string BANCOS { get; set; }
        public string OTROSIMPUESTOS { get; set; }
        public string IMPUESTOVENTA1 { get; set; }
        public string IMPUESTOVENTA2 { get; set; }
        public string IMPUESTOVENTA3 { get; set; }
        public string DIFCOSTOCOMPRA { get; set; }
        public string NOTASCRED { get; set; }
    }
}
