//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ulp_dl.aspel_sae80
{
    using System;
    using System.Collections.Generic;
    
    public partial class PARAM_GRAFICAS01
    {
        public int NUM_EMP { get; set; }
        public string AJUSTVALMAX { get; set; }
        public string GRAFICACUM { get; set; }
        public Nullable<int> NUMMAXVAL { get; set; }
        public Nullable<int> NUMSALTOS { get; set; }
        public string COPIARASCII { get; set; }
        public string COPIARLOTUS { get; set; }
        public string COPIAREXCEL { get; set; }
        public string COPIARCONENCAB { get; set; }
        public string COPIARCONTOTALES { get; set; }
    }
}
