//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ulp_dl.aspel_sae80
{
    using System;
    using System.Collections.Generic;
    
    public partial class PARAM_FACTURA01
    {
        public int NUM_EMP { get; set; }
        public string FACTURASINEXIST { get; set; }
        public string ALTACLIEPROVENCAPTURA { get; set; }
        public string ACUMCOMPVTASENLINEA { get; set; }
        public string MUESTRADESGKITS { get; set; }
        public string VENDCVESEC { get; set; }
        public string NOAFECDOCTOXCLIE { get; set; }
        public string ALTANUMSERIEENVENTAS { get; set; }
        public string FACTURARLOTPEDSINEXIST { get; set; }
        public string PERMITIRVTAPRODCADUCOS { get; set; }
        public string POLIZASENLINEAVTAS { get; set; }
        public string POLIZASENLINEADEVOL { get; set; }
        public Nullable<int> NUMDESCUENTOS { get; set; }
        public Nullable<int> NUMIMPUESTO { get; set; }
        public Nullable<int> NUMCPTOCOMPVTASPLAZOS { get; set; }
        public Nullable<int> NUMCPTOINTXCOMPVTAPLAZO { get; set; }
        public Nullable<int> NUMCPTORETCLIEPROV { get; set; }
        public Nullable<int> NUMMAXPART { get; set; }
        public string MANEJOFLETE { get; set; }
        public Nullable<double> MONTOFLETE { get; set; }
        public Nullable<double> IMPFLETE { get; set; }
        public Nullable<System.DateTime> FCHCIERREDOCTOS { get; set; }
        public string MODULO { get; set; }
        public Nullable<int> ALMACENDEVOLUCION { get; set; }
        public string CONALMACENDEVOLUCION { get; set; }
        public Nullable<int> ALMADEVPER { get; set; }
        public string MODIFICARALMACEN { get; set; }
        public Nullable<int> REFORMAFISCAL2012 { get; set; }
        public Nullable<int> NUMCPTONOTAVTA { get; set; }
        public Nullable<int> NUMCPTOEFECTIVO { get; set; }
        public Nullable<int> NUMCPTOCAMBIO { get; set; }
        public string CAPTPRIMEROPROD { get; set; }
        public Nullable<int> ALMACENFACTGLOB { get; set; }
        public string POLIZASENLINEANOTACRED { get; set; }
    }
}
