//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ulp_dl.aspel_sae80
{
    using System;
    using System.Collections.Generic;
    
    public partial class PED_CLARO01
    {
        public string TIPO_DOC { get; set; }
        public string CVE_DOC { get; set; }
        public string DOC_SIG { get; set; }
        public string CVE_CLIE { get; set; }
        public string NOM_COMP { get; set; }
        public string DIRE_COMP { get; set; }
        public string CALLE_COMP { get; set; }
        public string COL_COMP { get; set; }
        public string CP_COMP { get; set; }
        public string CD_COMP { get; set; }
        public string EDO_COMP { get; set; }
        public string MUNI_COMP { get; set; }
        public string EDO_PED { get; set; }
        public Nullable<System.DateTime> F_COLOCA { get; set; }
        public Nullable<System.DateTime> F_AUTORIZA { get; set; }
        public string SKU { get; set; }
        public Nullable<System.DateTime> F_EMBAR { get; set; }
        public string NUM_GUIA { get; set; }
        public string PAQUET { get; set; }
        public Nullable<double> CANT_PROD { get; set; }
        public Nullable<double> CANT_PROD_PED { get; set; }
        public string TIP_DOC_E { get; set; }
        public Nullable<int> CVE_BITA { get; set; }
        public string BLOQ { get; set; }
        public string TIP_DOC_SIG { get; set; }
        public string ESTADO_SINC { get; set; }
        public Nullable<System.DateTime> F_ENTREGA { get; set; }
        public string OBS_ENVIO { get; set; }
        public Nullable<double> IMPORTE { get; set; }
        public string ENLAZADO { get; set; }
        public string STATUS { get; set; }
    }
}
