//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ulp_dl.aspel_sae80
{
    using System;
    using System.Collections.Generic;
    
    public partial class PED_AMAZON01
    {
        public string TIPO_DOC { get; set; }
        public string CVE_DOC { get; set; }
        public string TIP_DOC_SIG { get; set; }
        public string DOC_SIG { get; set; }
        public string STATUS { get; set; }
        public string MONED { get; set; }
        public Nullable<double> IMPORTE { get; set; }
        public string ESTADO_SINC { get; set; }
        public Nullable<System.DateTime> F_COMPRA { get; set; }
        public string TIP_DOC_E { get; set; }
        public Nullable<int> CVE_BITA { get; set; }
        public Nullable<System.DateTime> F_MODIFICACION { get; set; }
        public string MET_PAGO { get; set; }
        public string DETMET_PAGO { get; set; }
        public string CUMPLI { get; set; }
        public string NOM_COMP { get; set; }
        public string CALLE_COMP { get; set; }
        public string ENTRE_COMP { get; set; }
        public string YCALLE_COMP { get; set; }
        public string CD_COMP { get; set; }
        public string MUN_COMP { get; set; }
        public string PAIS_COMP { get; set; }
        public string DIS_COMP { get; set; }
        public string EDO_COMP { get; set; }
        public string CP_COMP { get; set; }
        public string BLOQ { get; set; }
        public string ENLAZADO { get; set; }
    }
}
