//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ulp_dl.aspel_sae80
{
    using System;
    using System.Collections.Generic;
    
    public partial class PED_MSTR
    {
        public int PEDIDO { get; set; }
        public string CLIENTE { get; set; }
        public System.DateTime FECHA { get; set; }
        public Nullable<double> DESCUENTO { get; set; }
        public string TERMINOS { get; set; }
        public Nullable<double> COMISION { get; set; }
        public string AGENTE { get; set; }
        public string ESTATUS { get; set; }
        public string REMITIDO { get; set; }
        public string CONSIGNADO { get; set; }
        public string OBSERVACIONES { get; set; }
        public Nullable<decimal> IMPORTE { get; set; }
        public Nullable<int> PRENDAS { get; set; }
        public Nullable<double> DESC_DADO { get; set; }
        public Nullable<int> LISTA { get; set; }
        public string OC { get; set; }
        public Nullable<System.DateTime> FECHA_IMPRESION { get; set; }
        public string TIPO { get; set; }
        public Nullable<double> DS { get; set; }
        public Nullable<double> CMP { get; set; }
        public string FORMADEPAGOSAT { get; set; }
        public string USO_CFDI { get; set; }
        public string METODODEPAGO { get; set; }
        public Nullable<int> NUMERO_COTIZACION { get; set; }
    }
}
