//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ulp_dl.aspel_sae80
{
    using System;
    using System.Collections.Generic;
    
    public partial class PED_TEMP
    {
        public int PEDIDO { get; set; }
        public string MODELO { get; set; }
        public string DESCRIPCION { get; set; }
        public string TALLAS { get; set; }
        public string AGRUPADOR { get; set; }
        public int PRENDAS { get; set; }
        public Nullable<decimal> PRECIO { get; set; }
        public Nullable<decimal> IMPORTE { get; set; }
        public Nullable<decimal> PRE_PROCESOS { get; set; }
    }
}
