//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ulp_dl.aspel_sae80
{
    using System;
    using System.Collections.Generic;
    
    public partial class PED_DET
    {
        public int CONTADOR { get; set; }
        public int PEDIDO { get; set; }
        public string CODIGO { get; set; }
        public string DESCRIPCION { get; set; }
        public Nullable<decimal> PRECIO_PROD { get; set; }
        public Nullable<double> DESCUENTO { get; set; }
        public Nullable<int> CANTIDAD { get; set; }
        public Nullable<decimal> PREC_PROCESO { get; set; }
        public string PROCESOS { get; set; }
        public Nullable<decimal> SUBTOTAL { get; set; }
        public Nullable<decimal> PRECIO_LISTA { get; set; }
        public string AGRUPADOR { get; set; }
    }
}
