//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ulp_dl.aspel_sae80
{
    using System;
    using System.Collections.Generic;
    
    public partial class PED_TIEND01
    {
        public string TIPO_DOC { get; set; }
        public string CVE_DOC { get; set; }
        public string DOC_SIG { get; set; }
        public string CVE_TIENDA { get; set; }
        public string CVE_CLIE { get; set; }
        public string ESTADO { get; set; }
        public string STATUS { get; set; }
        public string CVE_VEND { get; set; }
        public Nullable<System.DateTime> F_ELAB { get; set; }
        public Nullable<System.DateTime> F_CONFIR { get; set; }
        public Nullable<System.DateTime> F_VIGEN { get; set; }
        public Nullable<System.DateTime> F_LAST_UPDATE { get; set; }
        public Nullable<double> IMPORTE { get; set; }
        public string ENLAZADO { get; set; }
        public string TIP_DOC_E { get; set; }
        public string CVE_MONED { get; set; }
        public Nullable<double> TIPCAMB { get; set; }
        public Nullable<int> CVE_BITA { get; set; }
        public string BLOQ { get; set; }
        public string TIP_DOC_SIG { get; set; }
        public string STATUS_SAE { get; set; }
        public string ESTADO_SINC { get; set; }
        public string MOD_ENVIO { get; set; }
        public string NICK_NAME { get; set; }
        public string CORREO { get; set; }
        public string NOMBRE_COMP { get; set; }
        public string APELLIDO_COMP { get; set; }
        public Nullable<System.DateTime> F_ENTREGA { get; set; }
        public Nullable<double> COST_ENVIO { get; set; }
        public Nullable<double> SUBTOT { get; set; }
        public Nullable<double> COMI_VENTA { get; set; }
        public string NUM_GUIA { get; set; }
        public string ENTREGADO { get; set; }
        public string OBS_ENVIO { get; set; }
        public string CVE_ENVIO { get; set; }
        public string TIP_DOC_SEG { get; set; }
        public string DOC_SEG { get; set; }
        public Nullable<int> CVE_INFO { get; set; }
        public string OPCION_ENVIO { get; set; }
        public string PACK_ID { get; set; }
    }
}
