//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ulp_dl.aspel_sae80
{
    using System;
    using System.Collections.Generic;
    
    public partial class POLI01
    {
        public int CVE_POLIT { get; set; }
        public string DESCR { get; set; }
        public string ST { get; set; }
        public string CVE_INI { get; set; }
        public string CVE_FIN { get; set; }
        public string LIN_PROD { get; set; }
        public Nullable<double> VOL_MIN { get; set; }
        public string CLIE_D { get; set; }
        public string CLIE_H { get; set; }
        public string CLAS_CLIE { get; set; }
        public Nullable<System.DateTime> V_DFECH { get; set; }
        public Nullable<System.DateTime> V_HFECH { get; set; }
        public string T_POL { get; set; }
        public string PRC_MON { get; set; }
        public Nullable<int> LISTA_PREC { get; set; }
        public Nullable<double> VAL { get; set; }
        public Nullable<double> LIMUNIVTA { get; set; }
        public Nullable<double> NUMUNIVEN { get; set; }
        public string CVE_ZONA { get; set; }
        public Nullable<int> CVE_ALM { get; set; }
        public string DEBAJO_MIN { get; set; }
        public string UUID { get; set; }
        public Nullable<System.DateTime> VERSION_SINC { get; set; }
    }
}
