//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ulp_dl.aspel_sae80
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRECIOS01
    {
        public int CVE_PRECIO { get; set; }
        public string DESCRIPCION { get; set; }
        public Nullable<int> CVE_BITA { get; set; }
        public string STATUS { get; set; }
        public string UUID { get; set; }
        public Nullable<System.DateTime> VERSION_SINC { get; set; }
        public string CON_IMPU { get; set; }
    }
}
