//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ulp_dl.aspel_sae80
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROD_INSUMOS01
    {
        public string CVE_ART { get; set; }
        public string DESCRIPCION { get; set; }
        public string UNI_MED { get; set; }
        public Nullable<double> COSTO_UNIT { get; set; }
        public string TIPO { get; set; }
        public string CLASIF { get; set; }
        public string TIPOG { get; set; }
        public string STATUS { get; set; }
    }
}
