//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ulp_dl.aspel_sae80
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROD_FABDIRECTA01
    {
        public string CVE_ORD { get; set; }
        public Nullable<double> CANTIDAD { get; set; }
        public string TIPOMOV { get; set; }
        public Nullable<int> ALMACEN { get; set; }
        public string COMPONENTE { get; set; }
        public Nullable<double> COSTO { get; set; }
    }
}
