//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ulp_dl.aspel_sae80
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROD_ESQINDI01
    {
        public int CVE_ESQIMPU { get; set; }
        public string DESCRIPESQ { get; set; }
        public Nullable<double> G1_FACTORUNIT { get; set; }
        public Nullable<double> G2_FACTORUNIT { get; set; }
        public string G3_COMPONENTE { get; set; }
        public Nullable<double> G3_FACTORUNIT { get; set; }
    }
}
