//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ulp_dl.aspel_sae80
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROD_PARAMSIS01
    {
        public int NUMEMPR { get; set; }
        public Nullable<int> MANEJA_PROC_PROD { get; set; }
        public Nullable<int> ORD_MAN_INTEG { get; set; }
        public Nullable<int> ACT_INTEGRADA { get; set; }
        public Nullable<int> CAP_COSTOS_IND { get; set; }
        public Nullable<int> NUM_ORDEN_SEC { get; set; }
        public Nullable<int> REDONDEO_PESOS { get; set; }
        public Nullable<int> COMP_VS_HCOSTOS { get; set; }
        public Nullable<int> CAP_ALM_EN_PART { get; set; }
        public Nullable<int> CAMB_METODO_COST { get; set; }
        public Nullable<int> COSTOUNIT_ENTPAR { get; set; }
        public Nullable<int> NUM_DECIMALES { get; set; }
        public Nullable<double> PORC_ENT_PARCIAL { get; set; }
        public string SAE_VERSION { get; set; }
        public Nullable<int> SAE_NUMEMPR { get; set; }
        public Nullable<int> SAE_MATPRIMA { get; set; }
        public Nullable<int> SAE_PRODUCTOTERM { get; set; }
        public Nullable<int> SAE_ENT_FABRICA { get; set; }
        public Nullable<int> SAE_SAL_FABRICA { get; set; }
        public Nullable<int> SAE_DEV_ALM { get; set; }
        public Nullable<int> G1_TIPO_PRORRA { get; set; }
        public string G1_COMPONENTE { get; set; }
        public Nullable<double> G1_FACTORUNIT { get; set; }
        public Nullable<int> G2_TIPO_PRORRA { get; set; }
        public string G2_COMPONENTE { get; set; }
        public Nullable<double> G2_FACTORUNIT { get; set; }
        public Nullable<int> G3_TIPO_PRORRA { get; set; }
        public string G3_COMPONENTE { get; set; }
        public Nullable<double> G3_FACTORUNIT { get; set; }
        public Nullable<int> CVE_PLANTA_ASIG { get; set; }
        public string LISTA_PLANTAS { get; set; }
        public Nullable<int> MUESTRA_TABLERO { get; set; }
    }
}
