//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ulp_dl.aspel_sae80
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROD_PROCESOS01
    {
        public string CVE_PROC { get; set; }
        public string DESCRIPCION { get; set; }
        public string LOCALIZA { get; set; }
        public string STATUS { get; set; }
        public string CTA_COI { get; set; }
        public Nullable<int> DEPTO { get; set; }
        public Nullable<double> MONTO_CAP { get; set; }
    }
}
