//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ulp_dl.aspel_sae80
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROD_ENTRADAFAB01
    {
        public int CVE_ENT { get; set; }
        public string CVE_ORD { get; set; }
        public string PROCESO { get; set; }
        public Nullable<System.DateTime> FECHMOV { get; set; }
        public Nullable<double> CANTENT { get; set; }
        public Nullable<int> ALMACEN { get; set; }
        public string COMPONENTE { get; set; }
        public string TIPOCMP { get; set; }
        public string CVE_TRAB { get; set; }
        public Nullable<double> COSTOUNIT { get; set; }
        public Nullable<double> COSTOEST { get; set; }
        public string REFERENCIA { get; set; }
        public Nullable<int> NUMLOTE { get; set; }
        public Nullable<int> ACTSAE { get; set; }
        public Nullable<double> CANTDEV { get; set; }
        public string TIPOMOV { get; set; }
        public Nullable<int> CVE_OBS { get; set; }
        public Nullable<int> CVE_PLANTA { get; set; }
        public int REG_MOV { get; set; }
        public string CVE_ART { get; set; }
    }
}
