//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ulp_dl.aspel_sae80
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROD_PRODTERM_DET01
    {
        public string CVE_ART { get; set; }
        public int NUMCOMPO { get; set; }
        public string PROCESO { get; set; }
        public string COMPONENTE { get; set; }
        public Nullable<int> ALMACEN { get; set; }
        public Nullable<int> TIPOCOMP { get; set; }
        public Nullable<double> CANTIDAD { get; set; }
        public Nullable<double> COSTOU { get; set; }
        public string TIPOG { get; set; }
        public Nullable<double> TIEMPOPROC { get; set; }
        public Nullable<int> SECUENCIA { get; set; }
        public Nullable<int> CVE_OBS { get; set; }
        public string TIPOCOMPONENTE { get; set; }
        public Nullable<double> TOTALCOSTOUNITARIO { get; set; }
        public int CVE_PLANTA { get; set; }
    }
}
