//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ulp_dl.aspel_sae80
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROD_ENTREGAPARCIAL01
    {
        public string CVE_ORD { get; set; }
        public string DOCUMENTO { get; set; }
        public Nullable<System.DateTime> FECHENTREGA { get; set; }
        public Nullable<int> ALMACEN { get; set; }
        public Nullable<System.DateTime> FECHMOV { get; set; }
        public Nullable<double> CANTENT { get; set; }
        public Nullable<double> INDUNIT { get; set; }
        public Nullable<double> COSTOUNIT { get; set; }
        public Nullable<double> TOTALUNIT { get; set; }
        public Nullable<double> TOTALENTREGA { get; set; }
        public Nullable<double> CSTTOTAL_MAT { get; set; }
        public Nullable<double> CSTTOTAL_MO { get; set; }
        public Nullable<double> CSTTOTAL_OTRSINS { get; set; }
        public int CVE_PLANTA { get; set; }
    }
}
