//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ulp_dl.aspel_sae80
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROD_SUSTITUTOS01
    {
        public int CVESEC { get; set; }
        public string CVE_MATPRI { get; set; }
        public string TIPO { get; set; }
        public string CVE_SUST { get; set; }
        public Nullable<double> EQUIVALE { get; set; }
        public Nullable<double> ES_A { get; set; }
        public string STATUS { get; set; }
    }
}
