//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ulp_dl.aspel_sae80
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROD_ORDENES01
    {
        public string CVE_ORD { get; set; }
        public string CVE_ART { get; set; }
        public Nullable<double> CANTIDAD { get; set; }
        public Nullable<int> PRIORIDAD { get; set; }
        public System.DateTime FCAPTURA { get; set; }
        public Nullable<System.DateTime> FENTREGA { get; set; }
        public Nullable<System.DateTime> FINICIAL { get; set; }
        public Nullable<System.DateTime> FTERMINA { get; set; }
        public Nullable<double> CANTTERM { get; set; }
        public Nullable<double> TGASDIR { get; set; }
        public Nullable<double> TGASIND { get; set; }
        public Nullable<System.DateTime> FULTMOV { get; set; }
        public string REFERENCIA { get; set; }
        public Nullable<double> COSTEST { get; set; }
        public Nullable<int> TIPOCOSTEO { get; set; }
        public Nullable<int> TIPOORD { get; set; }
        public string STATUS { get; set; }
        public string STATUSAVANCE { get; set; }
        public string PROCESO { get; set; }
        public Nullable<int> NUMUSU { get; set; }
        public Nullable<int> REGSERIE { get; set; }
        public Nullable<int> OCUPADO { get; set; }
        public Nullable<int> ACT_SAE { get; set; }
        public Nullable<int> HRSXDIA { get; set; }
        public Nullable<int> CVE_OBS { get; set; }
        public string CVELOTE { get; set; }
        public Nullable<System.DateTime> FCHCADUC { get; set; }
        public Nullable<System.DateTime> FCHPRODUC { get; set; }
        public Nullable<int> REG_LTPD { get; set; }
        public string STATUSBAJA { get; set; }
        public byte[] PROD_IMAGEN { get; set; }
        public Nullable<int> CVE_ESQ_INDI { get; set; }
        public int CVE_PLANTA { get; set; }
    }
}
