//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ulp_dl.aspel_sae80
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROD_SERIESXCOMP01
    {
        public int CVESEC { get; set; }
        public string CVE_ORD { get; set; }
        public string COMPONENTE { get; set; }
        public string NUM_SER { get; set; }
        public int ALMACEN { get; set; }
        public string STATUS { get; set; }
        public int CVE_ENT { get; set; }
        public string TIPOMOV { get; set; }
        public int CVE_PLANTA { get; set; }
        public Nullable<int> REG_MOV { get; set; }
    }
}
