//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ulp_dl.aspel_sae80
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROD_MULTIPLANTAS01
    {
        public int CVE_PLANTA { get; set; }
        public string DESCR { get; set; }
        public Nullable<int> ALMACEN_PT { get; set; }
        public Nullable<int> ALMACEN_MP { get; set; }
        public string STATUS { get; set; }
        public Nullable<int> CONCEPTO_EF { get; set; }
        public Nullable<int> CONCEPTO_DEV { get; set; }
        public Nullable<int> CONCEPTO_SF { get; set; }
        public string PREFIJO { get; set; }
        public Nullable<int> ULT_CVE { get; set; }
    }
}
