//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ulp_dl.aspel_sae80
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROD_PRODTERM01
    {
        public string CVE_ART { get; set; }
        public Nullable<int> PT_ALMACEN { get; set; }
        public Nullable<int> ALMACENRC { get; set; }
        public Nullable<int> CVE_CPTO { get; set; }
        public string MOVRC { get; set; }
        public Nullable<double> COSTOE { get; set; }
        public Nullable<int> TIPOCOSTEO { get; set; }
        public Nullable<double> TIEMPOFAB { get; set; }
        public string IMAGEN { get; set; }
        public Nullable<double> LOTESUG { get; set; }
        public Nullable<int> NUM_PART { get; set; }
        public Nullable<int> PER_PROD { get; set; }
        public Nullable<int> NUMDIASPER { get; set; }
        public string OCUPADO { get; set; }
        public Nullable<int> COSTOMP { get; set; }
        public Nullable<int> CVE_OBS { get; set; }
        public string STATUS_REGISTRO { get; set; }
        public Nullable<int> CVE_ESQ_INDI { get; set; }
        public int CVE_PLANTA { get; set; }
    }
}
