//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ulp_dl.aspel_sae80
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROV01
    {
        public string CLAVE { get; set; }
        public string STATUS { get; set; }
        public string NOMBRE { get; set; }
        public string RFC { get; set; }
        public string CALLE { get; set; }
        public string NUMINT { get; set; }
        public string NUMEXT { get; set; }
        public string CRUZAMIENTOS { get; set; }
        public string CRUZAMIENTOS2 { get; set; }
        public string COLONIA { get; set; }
        public string CODIGO { get; set; }
        public string LOCALIDAD { get; set; }
        public string MUNICIPIO { get; set; }
        public string ESTADO { get; set; }
        public string CVE_PAIS { get; set; }
        public string NACIONALIDAD { get; set; }
        public string TELEFONO { get; set; }
        public string CLASIFIC { get; set; }
        public string FAX { get; set; }
        public string PAG_WEB { get; set; }
        public string CURP { get; set; }
        public string CVE_ZONA { get; set; }
        public string CON_CREDITO { get; set; }
        public Nullable<int> DIASCRED { get; set; }
        public Nullable<double> LIMCRED { get; set; }
        public Nullable<int> CVE_BITA { get; set; }
        public string ULT_PAGOD { get; set; }
        public Nullable<double> ULT_PAGOM { get; set; }
        public Nullable<System.DateTime> ULT_PAGOF { get; set; }
        public string ULT_COMPD { get; set; }
        public Nullable<double> ULT_COMPM { get; set; }
        public Nullable<System.DateTime> ULT_COMPF { get; set; }
        public Nullable<double> SALDO { get; set; }
        public Nullable<double> VENTAS { get; set; }
        public Nullable<double> DESCUENTO { get; set; }
        public Nullable<int> TIP_TERCERO { get; set; }
        public Nullable<int> TIP_OPERA { get; set; }
        public Nullable<int> CVE_OBS { get; set; }
        public string CUENTA_CONTABLE { get; set; }
        public Nullable<int> FORMA_PAGO { get; set; }
        public string BENEFICIARIO { get; set; }
        public string TITULAR_CUENTA { get; set; }
        public string BANCO { get; set; }
        public string SUCURSAL_BANCO { get; set; }
        public string CUENTA_BANCO { get; set; }
        public string CLABE { get; set; }
        public string DESC_OTROS { get; set; }
        public string IMPRIR { get; set; }
        public string MAIL { get; set; }
        public Nullable<int> NIVELSEC { get; set; }
        public string ENVIOSILEN { get; set; }
        public string EMAILPRED { get; set; }
        public string MODELO { get; set; }
        public Nullable<double> LAT { get; set; }
        public Nullable<double> LON { get; set; }
        public Nullable<int> VAL_RFC { get; set; }
        public string REG_FISC { get; set; }
    }
}
