//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ulp_dl.aspel_sae80
{
    using System;
    using System.Collections.Generic;
    
    public partial class SOLICITUDES_ESPECIALES
    {
        public int SOLICITUD { get; set; }
        public string CLIENTE { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
        public string AGENTE { get; set; }
        public Nullable<int> PRENDAS_LINEA { get; set; }
        public Nullable<int> PRENDAS_ESP { get; set; }
        public string GENERO { get; set; }
        public string TIPO_PRENDA { get; set; }
        public string COMPOSICION_TELA { get; set; }
        public string COLOR { get; set; }
        public string ESPECIFICACIONES { get; set; }
        public string TALLAS { get; set; }
        public string PLAZO_ENTREGA { get; set; }
        public decimal PRECIO_ASIGNADO { get; set; }
        public string CODIGO_COTIZACION { get; set; }
        public string CODIGOS_ASIGNADOS { get; set; }
        public string OBSERVACIONES_PROGRAMACION { get; set; }
        public string ESTATUS { get; set; }
    }
}
