//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ulp_dl.aspel_sae80
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEMP1_
    {
        public string TEMP1_INDICE { get; set; }
        public string TEMP1_AD_NAME { get; set; }
        public string TEMP1_AGENTE { get; set; }
        public string TEMP1_MODELO { get; set; }
        public Nullable<int> TEMP1_CMT_PEDIDO { get; set; }
        public Nullable<int> TEMP1_CANTIDAD { get; set; }
        public string TEMP1_CMT_COMO { get; set; }
        public string TEMP1_CMT_AGRUPADOR { get; set; }
        public Nullable<int> TEMP1_PUNTADAS { get; set; }
        public Nullable<decimal> TEMP1_COSTOVENTA { get; set; }
        public string TEMP1_PRECIOVENTA { get; set; }
        public Nullable<decimal> TEMP1_COSTOTOTALVENTA { get; set; }
        public string TEMP1_PRECIOTOTALVENTA { get; set; }
        public Nullable<int> TEMP1_CMTINDX { get; set; }
    }
}
