//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ulp_dl.aspel_sae80
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIOS
    {
        public int ID_USUARIO { get; set; }
        public string NOMBRE { get; set; }
        public string CLAVE { get; set; }
        public string PASSWORD { get; set; }
        public string ACCESO { get; set; }
        public string TIPO_USUARIO { get; set; }
        public string GERENTE { get; set; }
        public Nullable<int> INDICE { get; set; }
        public string CLAVE_TEL { get; set; }
        public Nullable<decimal> PRESUPUESTO { get; set; }
        public Nullable<bool> ACTIVO { get; set; }
        public string DEPARTAMENTO { get; set; }
        public string SKIN { get; set; }
    }
}
