//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ulp_dl.aspel_sae80
{
    using System;
    using System.Collections.Generic;
    
    public partial class VEND01
    {
        public string CVE_VEND { get; set; }
        public string STATUS { get; set; }
        public string NOMBRE { get; set; }
        public Nullable<double> COMI { get; set; }
        public string CLASIFIC { get; set; }
        public string CORREOE { get; set; }
        public string UUID { get; set; }
        public Nullable<System.DateTime> VERSION_SINC { get; set; }
    }
}
