//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ulp_dl.aspel_sae80
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZONA01
    {
        public string CVE_ZONA { get; set; }
        public string CVE_PADRE { get; set; }
        public string TEXTO { get; set; }
        public string TNODO { get; set; }
        public string CTA_CONT { get; set; }
        public Nullable<double> IMPUEFLETE { get; set; }
        public Nullable<double> MONTOFLETE { get; set; }
        public string FORMULA { get; set; }
        public string STATUS { get; set; }
    }
}
