//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ulp_dl.SIPNegocio
{
    using System;
    using System.Collections.Generic;
    
    public partial class COST_ENLA
    {
        public int NUM_REG { get; set; }
        public string CVE_CLPV { get; set; }
        public string CVE_DOC { get; set; }
        public int PEDIDO { get; set; }
    }
}
