//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ulp_dl.SIPNegocio
{
    using System;
    using System.Collections.Generic;

    public partial class LogUPPedidos
    {
        public int UID { get; set; }
        public int TRAN_ID { get; set; }
        public string WIN_USER { get; set; }
        public string SIP80_USER { get; set; }
        public string PC { get; set; }
        public System.DateTime DATE { get; set; }
        public string ACCION { get; set; }
        public string PANTALLA { get; set; }
        public Nullable<int> ID { get; set; }
        public Nullable<double> PEDIDO { get; set; }
        public string COD_CLIENTE { get; set; }
        public Nullable<System.DateTime> F_VENCIMIENTO { get; set; }
        public Nullable<System.DateTime> F_VENCIMIENTO2 { get; set; }
        public Nullable<System.DateTime> F_ESTANDAR { get; set; }
        public string PROCESOS { get; set; }
        public string COMENTARIOS { get; set; }
        public Nullable<System.DateTime> F_CAPT { get; set; }
        public Nullable<System.DateTime> F_IMPRESION { get; set; }
        public Nullable<System.DateTime> F_GESTION { get; set; }
        public Nullable<System.DateTime> F_CAPT_ASPEL { get; set; }
        public Nullable<System.DateTime> F_CREDITO { get; set; }
        public Nullable<System.DateTime> F_ASIG_RUTA { get; set; }
        public Nullable<System.DateTime> F_LIBERADO { get; set; }
        public Nullable<System.DateTime> F_SURTIDO { get; set; }
        public Nullable<System.DateTime> F_BORDADO { get; set; }
        public Nullable<System.DateTime> F_COSTURA { get; set; }
        public Nullable<System.DateTime> F_CORTE { get; set; }
        public Nullable<System.DateTime> F_ESTAMPADO { get; set; }
        public Nullable<System.DateTime> F_INICIALES { get; set; }
        public Nullable<System.DateTime> F_EMPAQUE { get; set; }
        public Nullable<System.DateTime> F_EMBARQUE { get; set; }
        public Nullable<System.DateTime> FECHAPEDIDO { get; set; }
        public Nullable<System.DateTime> FECHARUTA { get; set; }
        public string GUIA { get; set; }
        public Nullable<int> CAJAS { get; set; }
        public string CHOFER { get; set; }
        public string DEPARTAMENTO { get; set; }
        public string DESTINO { get; set; }
        public string OBSERVACIONES { get; set; }
        public string ESTATUS { get; set; }
        public string TRANSPORTE { get; set; }
        public string COM_SURTIDO { get; set; }
        public string COM_BORDADO { get; set; }
        public string COM_COSTURA { get; set; }
        public string COM_CORTE { get; set; }
        public string COM_ESTAMPADO { get; set; }
        public string COM_INICIALES { get; set; }
        public string COM_EMPAQUE { get; set; }
        public string COM_CREDITO { get; set; }
        public string ESTATUS_UPPEDIDOS { get; set; }
        public Nullable<System.DateTime> F_ENTREGADO { get; set; }
        public string COM_ENTREGA { get; set; }
        public Nullable<System.DateTime> F_COORDINADOR { get; set; }
        public Nullable<System.DateTime> F_GV { get; set; }
        public Nullable<System.DateTime> F_DIRECCION { get; set; }
    }
}
