//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ulp_dl.SIPNegocio
{
    using System;
    using System.Collections.Generic;
    
    public partial class VersionesDetalle
    {
        public int Id { get; set; }
        public string VersionesDescripcion { get; set; }
        public int VersionesPrincipalId { get; set; }
    
        public virtual VersionesPrincipal VersionesPrincipal { get; set; }
    }
}
