//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ulp_dl.SIPNegocio
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Clientes
    {
        public string CLAVE { get; set; }
        public string RFC { get; set; }
        public string NOMBRE_CLIENTE { get; set; }
        public string DIRECCION { get; set; }
        public string TELEFONO { get; set; }
        public string CODIGO { get; set; }
        public string ATENCION { get; set; }
        public string NOMBRE_VENDEDOR { get; set; }
        public double DESCUENTO { get; set; }
        public int DIAS_CRE { get; set; }
        public double LIM_CRED { get; set; }
        public double CRED_DISPO { get; set; }
        public double SALDO { get; set; }
        public string TEXTO { get; set; }
        public string FCH_ULTCOM { get; set; }
        public Nullable<double> PZAULTANIO { get; set; }
        public string CL8 { get; set; }
        public string CVE_VEND { get; set; }
        public string STATUS { get; set; }
    }
}
