//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ulp_dl.SIPNegocio
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_EstadoCuenta
    {
        public string CVE_CLIE { get; set; }
        public string Concepto { get; set; }
        public string Documento { get; set; }
        public string Referencia { get; set; }
        public string Aplicado { get; set; }
        public string Vencido { get; set; }
        public string Elaborado { get; set; }
        public double Cargo { get; set; }
        public double Abono { get; set; }
        public Nullable<int> Dias { get; set; }
    }
}
