//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ulp_dl.SIPNegocio
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Inventario
    {
        public string CLV_ART { get; set; }
        public string DESCR { get; set; }
        public Nullable<double> PRECIO1 { get; set; }
        public string TIPO_ELE { get; set; }
    }
}
